export const defaultDelimiters = [
  {left: "$$", right: "$$", display: true},
  {left: "$", right: "$", display: false},
  {left: "\\(", right: "\\)", display: false},
  {left: "\\begin{equation}", right: "\\end{equation}", display: true},
  {left: "\\begin{align}", right: "\\end{align}", display: true},
  {left: "\\begin{alignat}", right: "\\end{alignat}", display: true},
  {left: "\\begin{gather}", right: "\\end{gather}", display: true},
  {left: "\\begin{CD}", right: "\\end{CD}", display: true},
  {left: "\\[", right: "\\]", display: true}
];

export const macros = {
  "\\algbigoplus": "\\hat{\\bigoplus}",
  "\\algbigotimes": "\\hat{\\bigotimes}",
  "\\algoplus": "\\hat{\\oplus}",
  "\\algotimes": "\\hat{\\otimes}",
  "\\essinf": "\\mathrm{ess \\, inf}",
  "\\esssup": "\\mathrm{ess \\, sup}",
  "\\opexistsone": "\\exists!",
  "\\opexists": "\\exists",
  "\\opforall": "\\forall",
  "\\primedsum": "\\sideset{}{^{\\prime}}\\sum",
  "\\slim": "\\mathrm{s} \\myhyphen \\lim",
  "\\wlim": "\\mathrm{w} \\myhyphen \\lim",
  "\\Ad": "\\mathrm{Ad}",
  "\\Aff": "\\mathrm{Aff}",
  "\\Ann": "\\mathrm{Ann}",
  "\\Ass": "\\mathrm{Ass}",
  "\\Aut": "\\mathrm{Aut}",
  "\\Cl": "\\mathrm{Cl}",
  "\\Coim": "\\mathrm{Coim}",
  "\\Coker": "\\mathrm{Coker}",
  "\\Deck": "\\mathrm{Deck}",
  "\\Der": "\\mathrm{Der}",
  "\\Diff": "\\mathrm{Diff}",
  "\\Div": "\\mathrm{Div}",
  "\\Dom": "\\mathrm{Dom}",
  "\\Endskew": "\\mathrm{End}_{\\mathrm{skew}}",
  "\\End": "\\mathrm{End}",
  "\\Even": "\\mathrm{Even}",
  "\\Ext": "\\mathrm{Ext}",
  "\\Frac": "\\mathrm{Frac}",
  "\\GL": "\\mathrm{GL}",
  "\\Gal": "\\mathrm{Gal}",
  "\\Gammafin": "\\Gamma_{\\rmfin}",
  "\\Herm": "\\mathrm{Herm}",
  "\\Hol": "\\mathrm{Hol}",
  "\\Hom": "\\mathrm{Hom}",
  "\\Image": "\\mathrm{Im}",
  "\\Imaginary": "\\mathrm{Im}",
  "\\Ind": "\\mathrm{Ind}",
  "\\Inn": "\\mathrm{Inn}",
  "\\Int": "\\mathrm{Int}",
  "\\Inv": "\\mathrm{Inv}",
  "\\Isom": "\\mathrm{Isom}",
  "\\Iso": "\\mathrm{Iso}",
  "\\Jac": "\\mathrm{Jac}",
  "\\Ker": "\\mathrm{Ker}",
  "\\Log": "\\mathrm{Log}",
  "\\Mod": "\\mathsf{Mod}",
  "\\Odd": "\\mathrm{Odd}",
  "\\Op": "\\mathrm{Op}",
  "\\Out": "\\mathrm{Out}",
  "\\PDO": "\\mathrm{PDO}",
  "\\Per": "\\mathrm{Per}",
  "\\Pic": "\\mathrm{Pic}",
  "\\Powfin": "\\mathrm{Pow}_{\\mathrm{fin}}",
  "\\Pow": "\\mathrm{Pow}",
  "\\Rad": "\\mathrm{Rad}",
  "\\Real": "\\mathrm{Re}",
  "\\Reg": "\\mathrm{Reg}",
  "\\Res": "\\mathrm{Res}",
  "\\Rev": "\\mathrm{Rev}",
  "\\Ric": "\\mathrm{Ric}",
  "\\SL": "\\mathrm{SL}",
  "\\Sch": "\\mathrm{Sch}",
  "\\Spec": "\\mathrm{Spec}",
  "\\Spinc": "\\mathrm{Spin}_{\\mathrm{c}}",
  "\\Supp": "\\mathrm{Supp}",
  "\\Tor": "\\mathrm{Tor}",
  "\\Trace": "\\mathrm{Tr}",
  "\\Vol": "\\mathrm{Vol}",
  "\\adj": "\\mathrm{adj}",
  "\\ad": "\\mathrm{ad}",
  "\\aff": "\\mathrm{aff}",
  "\\apply": "\\triangleright",
  "\\applyleft": "\\triangleleft",
  "\\arccosh": "\\mathrm{arccosh}",
  "\\arcsinh": "\\mathrm{arcsinh}",
  "\\arctanh": "\\mathrm{arctanh}",
  "\\argmax": "\\mathrm{argmax}",
  "\\bbCl": "\\bbC \\mathrm{l}",
  "\\bigextprod": "\\bigwedge\\nolimits",
  "\\card": "\\mathrm{card}",
  "\\charOfField": "\\mathrm{char}",
  "\\cis": "\\mathrm{cis}",
  "\\closedconv": "\\overline{\\conv}",
  "\\closeddom": "\\overline{\\dom}",
  "\\closedker": "\\overline{\\ker}",
  "\\closedran": "\\overline{\\ran}",
  "\\closedspan": "\\overline{\\mathrm{span}}",
  "\\clos": "\\mathrm{clos}",
  "\\clo": "\\mathrm{clo}",
  "\\cn": "\\mathrm{cn}",
  "\\cod": "\\mathrm{cod}",
  "\\cof": "\\mathrm{cof}",
  "\\coker": "\\mathrm{coker}",
  "\\comp": "\\circ",
  "\\compleft": "\\mathrm{«}",
  "\\compright": "\\mathrm{»}",
  "\\conv": "\\mathrm{conv}",
  "\\co": "\\mathrm{co}",
  "\\curl": "\\mathrm{curl}",
  "\\dftovfoneop": "\\sharp_1",
  "\\dftovfop": "\\sharp",
  "\\dftovftwoop": "\\sharp_2",
  "\\diag": "\\mathrm{diag}",
  "\\diam": "\\mathrm{diam}",
  "\\dimbbC": "\\mathrm{dim}_{\\bbC}",
  "\\dimbbR": "\\mathrm{dim}_{\\bbR}",
  "\\dimension": "\\mathrm{dim}",
  "\\divergence": "\\mathrm{div}",
  "\\divs": "\\mathrm{Div}",
  "\\dn": "\\mathrm{dn}",
  "\\dom": "\\mathrm{dom}",
  "\\edivs": "\\mathrm{Div}_+",
  "\\essran": "\\mathrm{ess \\, ran}",
  "\\exteriorproduct": "\\wedge",
  "\\grad": "\\mathrm{grad}",
  "\\image": "\\mathrm{im}",
  "\\im": "\\mathrm{im}",
  "\\ind": "\\mathrm{ind}",
  "\\len": "\\mathrm{len}",
  "\\linearspan": "\\mathrm{span}",
  "\\mSpec": "\\mathrm{m} \\myhyphen \\mathrm{Spec}",
  "\\myex": "\\mathrm{ex}",
  "\\mylaplacian": "\\Delta",
  "\\nilrad": "\\mathrm{nilrad}",
  "\\obj": "\\mathrm{obj}",
  "\\opTr": "\\mathrm{Tr}",
  "\\opst": "\\mathrm{st}",
  "\\ord": "\\mathrm{ord}",
  "\\osc": "\\mathrm{osc}",
  "\\pathhomotopic": "\\dot{\\simeq}",
  "\\pdivs": "\\mathrm{Div}_{\\mathrm{princ}}",
  "\\picard": "\\mathrm{Pic}",
  "\\proj": "\\mathrm{Proj}",
  "\\rad": "\\mathrm{rad}",
  "\\rank": "\\mathrm{rank}",
  "\\ran": "\\mathrm{ran}",
  "\\res": "\\mathrm{res}",
  "\\rk": "\\mathrm{rk}",
  "\\rmYM": "\\mathrm{YM}",
  "\\rot": "\\mathrm{rot}",
  "\\sgn": "\\mathrm{sgn}",
  "\\sn": "\\mathrm{sn}",
  "\\supp": "\\mathrm{supp}",
  "\\symdiff": "\\raisebox{.2ex}{\\scalebox{0.8}{$\\triangle$}}",
  "\\tn": "\\mathrm{tn}",
  "\\touw": "\\stackrel{\\mathrm{uw}}{\\to}",
  "\\vftodfoneop": "\\flat_1",
  "\\vftodfop": "\\flat",
  "\\vftodftwoop": "\\flat_2",
  "\\vol": "\\mathrm{vol}",
  "\\mytwoheadrightarrowtail": "\\mathrel{\\rightarrowtail\\kern-1.9ex\\twoheadrightarrow}",
  "\\Ab": "\\mathsf{Ab}",
  "\\BC": "\\mathrm{BC}",
  "\\Bigrbk": "\\Big( #1 \\Big)",
  "\\CKnorms": "\\norms{#1}_{C(K)}",
  "\\CKnorm": "\\norm{#1}_{C(K)}",
  "\\CK": "C(K)",
  "\\CLipOmega": "C_{\\mathrm{Lip}} (\\Omega)",
  "\\CLip": "C_{\\mathrm{Lip}}",
  "\\COmeganorms": "\\norms{#1}_{C (\\Omega)}",
  "\\COmeganorm": "\\norm{#1}_{C (\\Omega)}",
  "\\COmega": "C (\\Omega)",
  "\\CX": "C (X)",
  "\\CbbbbRd": "\\Cbb(\\bbRd)",
  "\\Cbb": "C_{\\mathrm{bb}}",
  "\\CbinftyOmega": "\\Cb^{\\infty} (\\Omega)",
  "\\CbinftybbRN": "\\Cb^{\\infty} (\\bbRN)",
  "\\CbinftybbRd": "\\Cb^{\\infty} (\\bbRd)",
  "\\Cb": "C_{\\mathrm{b}}",
  "\\CcOmega": "C_{\\mathrm{c}} (\\Omega)",
  "\\CcX": "C_{\\mathrm{c}} (X)",
  "\\CcbbRNk": "C_{\\mathrm{c}} (\\bbRNk)",
  "\\CcbbRNx": "C_{\\mathrm{c}} (\\bbRNx)",
  "\\CcbbRN": "C_{\\mathrm{c}} (\\bbRN)",
  "\\CcbbRdk": "C_{\\mathrm{c}} (\\bbRdk)",
  "\\CcbbRdx": "C_{\\mathrm{c}} (\\bbRdx)",
  "\\CcbbRd": "C_{\\mathrm{c}} (\\bbRd)",
  "\\CcbbR": "C_{\\mathrm{c}} (\\bbR)",
  "\\CcinftyM": "\\Cc^{\\infty}(M)",
  "\\CcinftyOmega": "\\Cc^{\\infty} (\\Omega)",
  "\\CcinftyX": "\\Cc^{\\infty}(X)",
  "\\CcinftybbRNk": "\\Cc^{\\infty} (\\bbRNk)",
  "\\CcinftybbRNx": "\\Cc^{\\infty} (\\bbRNx)",
  "\\CcinftybbRN": "\\Cc^{\\infty} (\\bbRN)",
  "\\CcinftybbRdk": "\\Cc^{\\infty} (\\bbRdk)",
  "\\CcinftybbRdx": "\\Cc^{\\infty} (\\bbRdx)",
  "\\CcinftybbRd": "\\Cc^{\\infty} (\\bbRd)",
  "\\CcinftybbR": "\\Cc^{\\infty} (\\bbR)",
  "\\Ccinfty": "\\Cc^{\\infty}",
  "\\CclosureOmega": "C (\\closure{\\Omega})",
  "\\CconeOmega": "C_{\\mathrm{c}}^1 (\\Omega)",
  "\\CconebbRN": "C_{\\mathrm{c}}^1 (\\bbRN)",
  "\\CconebbRd": "C_{\\mathrm{c}}^1 (\\bbRd)",
  "\\CconebbR": "C_{\\mathrm{c}}^1 (\\bbR)",
  "\\Ccone": "C_{\\mathrm{c}}^1",
  "\\Cc": "C_{\\mathrm{c}}",
  "\\Cfin": "C_{\\mathrm{fin}}",
  "\\CinftyM": "C^{\\infty} (M)",
  "\\CinftyN": "C^{\\infty} (N)",
  "\\CinftyOmega": "C^{\\infty} (\\Omega)",
  "\\CinftyX": "C^{\\infty} (X)",
  "\\CinftybbRN": "C^{\\infty} (\\bbRN)",
  "\\CinftybbRd": "C^{\\infty} (\\bbRd)",
  "\\Cinfty": "C^{\\infty}",
  "\\CkM": "C^k(M)",
  "\\CkOmega": "C^k (\\Omega)",
  "\\CkalphaOmega": "C^{k + \\alpha} (\\Omega)",
  "\\CkcOmega": "\\Cc^k (\\Omega)",
  "\\CkcX": "C^k_{\\mathrm{c}} (X)",
  "\\CksigmaOmeganorm": "\\norms{#1}_{\\CksigmaOmega}",
  "\\CksigmaOmega": "C^{k, \\sigma} (\\Omega)",
  "\\CksigmabbRNnorms": "\\norm{#1}_{\\CksigmabbRN}",
  "\\CksigmabbRN": "C^{k, \\sigma} (\\bbRN)",
  "\\CksigmabbRdnorms": "\\norm{#1}_{\\CksigmabbRd}",
  "\\CksigmabbRd": "C^{k, \\sigma} (\\bbRd)",
  "\\Cksigmanorms": "\\norms{#1}_{\\Cksigma}",
  "\\Cksigmanorm": "\\norm{#1}_{\\Cksigma}",
  "\\Cksigma": "C^{k, \\sigma}",
  "\\CkzeroOmega": "C^k_0 (\\Omega)",
  "\\CkzeroX": "C^k_0 (X)",
  "\\Ck": "C^k",
  "\\ClM": "C^l(M)",
  "\\CmOmega": "C^m (\\Omega)",
  "\\CmcOmega": "\\Cc^m (\\Omega)",
  "\\Combination": "{}_{#1} \\mathrm{C}_{#2}",
  "\\CondE": "\\E{#1 \\middle| #2}",
  "\\CondPr": "\\rmPr{#1 \\middle\\Vert #2}",
  "\\CondP": "P \\rbk{#1 \\middle| #2}",
  "\\ConeOmega": "C^1 (\\Omega)",
  "\\Cone": "C^1",
  "\\Const": "\\mathrm{Const}",
  "\\Cov": "\\mathrm{Cov}\\rbk{#1}",
  "\\Cpolynomialxbarx": "\\bbC [x, \\overline{x}]",
  "\\Cpolynomialx": "\\bbC [x]",
  "\\CspecA": "C (\\spectrum{A})",
  "\\Cstar": "C^{*}",
  "\\CzeroOmega": "C_0 (\\Omega)",
  "\\CzeroXplus": "C_0 (X)_+",
  "\\CzeroX": "C_0 (X)",
  "\\CzerobbRNk": "C_0 (\\bbRNk)",
  "\\CzerobbRNx": "C_0 (\\bbRNx)",
  "\\CzerobbRN": "C_0 (\\bbRN)",
  "\\CzerobbRdk": "C_0 (\\bbRdk)",
  "\\CzerobbRdx": "C_0 (\\bbRdx)",
  "\\CzerobbRd": "C_0 (\\bbRd)",
  "\\Czero": "C_0",
  "\\DbbQ": "D_{\\bbQ}",
  "\\DonebbRd": "D^1 (\\bbRd)",
  "\\DonehalfbbRd": "D^{1/2} (\\bbRd)",
  "\\EPP": "\\mathbb{E}_{#1}^{#2} \\sqbk{#3}",
  "\\EPRket": "\\ket{\\mathrm{EPR}}",
  "\\EP": "\\mathbb{E}_{#1} \\sqbk{#2}",
  "\\EleqN": "E_{\\leq}(N)",
  "\\Expectation": "\\mathbb{E} \\sqbk{#1}",
  "\\E": "\\mathbb{E} \\sqbk{#1}",
  "\\GLbdd": "\\GL_{\\mathrm{bdd}}",
  "\\Gammab": "\\Gamma_{\\mathrm{b}}",
  "\\Gammaf": "\\Gamma_{\\mathrm{f}}",
  "\\Grp": "\\mathsf{Grp}",
  "\\HI": "H_{\\mathrm{I}}",
  "\\Hbfr": "H_{\\mathrm{b}, \\mathrm{fr}}",
  "\\Hb": "H_{\\mathrm{b}}",
  "\\HdRscrO": "H_{\\mathrm{dR, \\scrO}}",
  "\\HdR": "H_{\\mathrm{dR}}",
  "\\Hel": "H_{\\mathrm{el}}",
  "\\He": "H_{\\mathrm{e}}",
  "\\HkOmegabkts": "\\bkts{#1}{#2}_{H^ (\\Omega)}",
  "\\HkOmegabkt": "\\bkt{#1}{#2}_{H^ (\\Omega)}",
  "\\HkOmega": "\\Hk (\\Omega)",
  "\\Hkappa": "H^{\\kappa}",
  "\\HkbbRNk": "\\Hk (\\bbRNk)",
  "\\HkbbRNx": "\\Hk (\\bbRNx)",
  "\\HkbbRN": "\\Hk (\\bbRN)",
  "\\HkbbRdk": "\\Hk (\\bbRdk)",
  "\\HkbbRdx": "\\Hk (\\bbRdx)",
  "\\HkbbRd": "\\Hk (\\bbRd)",
  "\\Hk": "H^k",
  "\\HoneAbbRd": "H_A^1 (\\bbRd)",
  "\\HoneA": "H_A^1",
  "\\HoneOmegabkts": "\\bkts{#1}{#2}_{\\HoneOmega}",
  "\\HoneOmegabkt": "\\bkt{#1}{#2}_{\\HoneOmega}",
  "\\HoneOmeganorms": "\\norms{#1}_{\\HoneOmega}",
  "\\HoneOmeganorm": "\\norm{#1}_{\\HoneOmega}",
  "\\HoneOmega": "H^1 (\\Omega)",
  "\\HonebbRNbkts": "\\bkts{#1}{#2}_{\\HonebbRN}",
  "\\HonebbRNbkt": "\\bkt{#1}{#2}_{\\HonebbRN}",
  "\\HonebbRN": "H^1 (\\bbRN)",
  "\\HonebbRdbkts": "\\bkts{#1}{#2}_{\\HonebbRd}",
  "\\HonebbRdbkt": "\\bkt{#1}{#2}_{\\HonebbRd}",
  "\\HonebbRdknorms": "\\norms{#1}_{\\HonebbRdk}",
  "\\HonebbRdknorm": "\\norm{#1}_{\\HonebbRdk}",
  "\\HonebbRdk": "H^1 (\\bbRdk)",
  "\\HonebbRdnorms": "\\norms{#1}_{\\HonebbRd}",
  "\\HonebbRdnorm": "\\norm{#1}_{\\HonebbRd}",
  "\\HonebbRdxnorms": "\\norms{#1}_{\\HonebbRdx}",
  "\\HonebbRdxnorm": "\\norm{#1}_{\\HonebbRdx}",
  "\\HonebbRdx": "H^1 (\\bbRdx)",
  "\\HonebbRd": "H^1 (\\bbRd)",
  "\\HonehalfbbRdk": "H^{1/2} (\\bbRdk)",
  "\\HonehalfbbRdx": "H^{1/2} (\\bbRdx)",
  "\\HonehalfbbRd": "H^{1/2} (\\bbRd)",
  "\\HonehalfbbRthreeN": "H^{1/2} (\\bbRthreeN)",
  "\\HonehalfbbRthree": "H^{1/2} (\\bbRthree)",
  "\\Honehalf": "H^{1/2}",
  "\\HonezeroOmega": "H_0^1 (\\Omega)",
  "\\Honezero": "H_0^1",
  "\\Hone": "H^1",
  "\\Hrmac": "H_{\\rmac}",
  "\\Hrms": "H_{\\rms}",
  "\\HtwoOmegabkts": "\\bkts{#1}{#2}_{\\HtwoOmega}",
  "\\HtwoOmegabkt": "\\bkt{#1}{#2}_{\\HtwoOmega}",
  "\\HtwoOmega": "H^2 (\\Omega)",
  "\\HtwobbRNbkts": "\\bkts{#1}{#2}_{\\HtwobbRN}",
  "\\HtwobbRNbkt": "\\bkt{#1}{#2}_{\\HtwobbRN}",
  "\\HtwobbRN": "H^2 (\\bbRN)",
  "\\HtwobbRdbkts": "\\bkts{#1}{#2}_{\\HtwobbRd}",
  "\\HtwobbRdbkt": "\\bkt{#1}{#2}_{\\HtwobbRd}",
  "\\HtwobbRd": "H^2 (\\bbRd)",
  "\\HtwokM": "H^2_k(M)",
  "\\HtwokS": "H^2_k(S)",
  "\\Htwok": "H^2_k",
  "\\HtwolM": "H^2_l(M)",
  "\\HtwolS": "H^2_l(S)",
  "\\Htwol": "H^2_l",
  "\\Htwo": "H^2",
  "\\LI": "L_{\\mathrm{I}}",
  "\\Laurant": "#1 \\cbk{\\cbk{#2}}",
  "\\Lb": "L_{\\mathrm{b}}",
  "\\Le": "L_{\\mathrm{e}}",
  "\\LieGL": "\\mathrm{GL}",
  "\\LieMp": "\\mathrm{Mp}",
  "\\LieO": "\\mathrm{O}",
  "\\LieSL": "\\mathrm{SL}",
  "\\LieSO": "\\mathrm{SO}",
  "\\LieSU": "\\mathrm{SU}",
  "\\LieSpin": "\\mathrm{Spin}",
  "\\LieSp": "\\mathrm{Sp}",
  "\\LieU": "\\mathrm{U}",
  "\\LinftyKnorms": "\\norms{#1}_{L^{\\infty} (K)}",
  "\\LinftyKnorm": "\\norm{#1}_{L^{\\infty} (K)}",
  "\\LinftyOmeganorms": "\\norms{#1}_{L^{\\infty} (\\Omega)}",
  "\\LinftyOmeganorm": "\\norm{#1}_{L^{\\infty} (\\Omega)}",
  "\\LinftyOmega": "L^{\\infty} (\\Omega)",
  "\\LinftyX": "L^{\\infty}(X)",
  "\\LinftybbRNknorms": "\\norms{#1}_{L^{\\infty} (\\bbRNk)}",
  "\\LinftybbRNknorm": "\\norm{#1}_{L^{\\infty} (\\bbRNk)}",
  "\\LinftybbRNk": "L^{\\infty} (\\bbRNk)",
  "\\LinftybbRNnorms": "\\norms{#1}_{L^{\\infty} (\\bbRN)}",
  "\\LinftybbRNnorm": "\\norm{#1}_{L^{\\infty} (\\bbRN)}",
  "\\LinftybbRNxnorms": "\\norms{#1}_{L^{\\infty} (\\bbRNx)}",
  "\\LinftybbRNxnorm": "\\norm{#1}_{L^{\\infty} (\\bbRNx)}",
  "\\LinftybbRN": "L^{\\infty} (\\bbRN)",
  "\\LinftybbRdknorms": "\\norms{#1}_{L^{\\infty} (\\bbRdk)}",
  "\\LinftybbRdknorm": "\\norm{#1}_{L^{\\infty} (\\bbRdk)}",
  "\\LinftybbRdk": "L^{\\infty} (\\bbRdk)",
  "\\LinftybbRdnorms": "\\norms{#1}_{L^{\\infty} (\\bbRd)}",
  "\\LinftybbRdnorm": "\\norm{#1}_{L^{\\infty} (\\bbRd)}",
  "\\LinftybbRdxnorms": "\\norms{#1}_{L^{\\infty} (\\bbRdx)}",
  "\\LinftybbRdxnorm": "\\norm{#1}_{L^{\\infty} (\\bbRdx)}",
  "\\LinftybbRd": "L^{\\infty} (\\bbRd)",
  "\\LinftybbR": "L^{\\infty} (\\bbR)",
  "\\LinftyepbbRd": "L_{\\ep}^{\\infty} (\\bbRd)",
  "\\Linftynorms": "\\norms{#1}_{\\Linfty}",
  "\\Linftynorm": "\\norm{#1}_{\\Linfty}",
  "\\Linfty": "L^{\\infty}",
  "\\Lint": "\\mathrm{L} \\int",
  "\\Lipabss": "| #1 |_{\\mathrm{Lip}}",
  "\\Lipabs": "\\left|#1\\right|_{\\mathrm{Lip}}",
  "\\Lipnorms": "\\Vert #1 \\Vert_{\\mathrm{Lip}}",
  "\\Lipnorm": "\\left\\Vert #1 \\right\\Vert_{\\mathrm{Lip}}",
  "\\LoneOmega": "L^1 (\\Omega)",
  "\\LoneX": "L^1(X)",
  "\\LonebbRNknorms": "\\norms{#1}_{L^{1} (\\bbRNk)}",
  "\\LonebbRNknorm": "\\norm{#1}_{L^{1} (\\bbRNk)}",
  "\\LonebbRNk": "L^1 (\\bbRNk)",
  "\\LonebbRNnorms": "\\norms{#1}_{L^{1} (\\bbRN)}",
  "\\LonebbRNnorm": "\\norm{#1}_{L^{1} (\\bbRN)}",
  "\\LonebbRNxnorms": "\\norms{#1}_{L^{1} (\\bbRNx)}",
  "\\LonebbRNxnorm": "\\norm{#1}_{L^{1} (\\bbRNx)}",
  "\\LonebbRNx": "L^1 (\\bbRNx)",
  "\\LonebbRN": "L^1 (\\bbRN)",
  "\\LonebbRdknorms": "\\norms{#1}_{L^{1} (\\bbRdk)}",
  "\\LonebbRdknorm": "\\norm{#1}_{L^{1} (\\bbRdk)}",
  "\\LonebbRdk": "L^1 (\\bbRdk)",
  "\\LonebbRdnorms": "\\norms{#1}_{L^{1} (\\bbRd)}",
  "\\LonebbRdnorm": "\\norm{#1}_{L^{1} (\\bbRd)}",
  "\\LonebbRdxnorms": "\\norms{#1}_{L^{1} (\\bbRdx)}",
  "\\LonebbRdxnorm": "\\norm{#1}_{L^{1} (\\bbRdx)}",
  "\\LonebbRdx": "L^1 (\\bbRdx)",
  "\\LonebbRd": "L^1 (\\bbRd)",
  "\\LonebbR": "L^1 (\\bbR)",
  "\\LonelocOmega": "L_{\\mathrm{loc}}^1 (\\Omega)",
  "\\LonelocbbRN": "L_{\\mathrm{loc}}^1 (\\bbRN)",
  "\\LonelocbbRd": "L_{\\mathrm{loc}}^1 (\\bbRd)",
  "\\Loneloc": "L_{\\mathrm{loc}}^1",
  "\\Lonenorms": "\\norms{#1}_{\\Lone}",
  "\\Lonenorm": "\\norm{#1}_{\\Lone}",
  "\\Lone": "L^1",
  "\\LpOmeganorms": "\\norms{#1}_{L^{p} (\\Omega)}",
  "\\LpOmeganorm": "\\norm{#1}_{L^{p} (\\Omega)}",
  "\\LpOmega": "L^{p} (\\Omega)",
  "\\LpX": "L^{p} (X)",
  "\\LpbbRNnorms": "\\norms{#1}_{L^{p} (\\bbRN)}",
  "\\LpbbRNnorm": "\\norm{#1}_{L^{p} (\\bbRN)}",
  "\\LpbbRN": "L^{p} (\\bbRN)",
  "\\LpbbRdnorms": "\\norms{#1}_{\\LpbbRd}",
  "\\LpbbRdnorm": "\\norm{#1}_{\\LpbbRd}",
  "\\LpbbRd": "L^{p} (\\bbRd)",
  "\\LpbbR": "L^{p} (\\bbR)",
  "\\LplocOmega": "L^{p}_{\\mathrm{loc}} (\\Omega)",
  "\\LplocbbRd": "L^{p}_{\\mathrm{loc}} (\\bbRd)",
  "\\Lploc": "L_{\\mathrm{loc}}^p",
  "\\Lpnorms": "\\norms{#1}_{\\Lp}",
  "\\Lpnorm": "\\norm{#1}_{\\Lp}",
  "\\LpwbbRd": "L^{p}_{\\mathrm{w}} (\\bbRd)",
  "\\Lpw": "L^{p}_{\\mathrm{w}}",
  "\\Lp": "L^{p}",
  "\\LqOmeganorms": "\\norms{#1}_{\\LqOmega}",
  "\\LqOmeganorm": "\\norm{#1}_{\\LqOmega}",
  "\\LqOmega": "L^{q} (\\Omega)",
  "\\LqX": "L^{q} (X)",
  "\\LqbbRNnorms": "\\norms{#1}_{\\LqbbRN}",
  "\\LqbbRNnorm": "\\norm{#1}_{\\LqbbRN}",
  "\\LqbbRN": "L^{q} (\\bbRN)",
  "\\LqbbRdnorms": "\\norms{#1}_{\\LqbbRd}",
  "\\LqbbRdnorm": "\\norm{#1}_{\\LqbbRd}",
  "\\LqbbRd": "L^{q} (\\bbRd)",
  "\\LqbbR": "L^{q} (\\bbR)",
  "\\Lqnorms": "\\norms{#1}_{\\Lq}",
  "\\Lqnorm": "\\norm{#1}_{\\Lq}",
  "\\Lq": "L^{q}",
  "\\LrOmega": "L^{r} (\\Omega)",
  "\\LrX": "L^{r} (X)",
  "\\LrbbRN": "L^{r} (\\bbRN)",
  "\\LrbbRd": "L^{r} (\\bbRd)",
  "\\LrlocOmega": "\\Lrloc (\\Omega)",
  "\\Lrloc": "L^{r}_{\\mathrm{loc}}",
  "\\Lr": "L^{r}",
  "\\Ls": "L^{s}",
  "\\LtwoM": "L^2 (M)",
  "\\LtwoOmegabkts": "\\langle #1,\\,#2 \\rangle_{\\LtwoOmega}",
  "\\LtwoOmegabkt": "\\left\\langle #1,\\,#2 \\right\\rangle_{\\LtwoOmega}",
  "\\LtwoOmeganorms": "\\norms{#1}_{L^2 (\\Omega)}",
  "\\LtwoOmeganorm": "\\norm{#1}_{L^2 (\\Omega)}",
  "\\LtwoOmegaphi": "L^2 (\\Omega, \\phi)",
  "\\LtwoOmega": "L^2 (\\Omega)",
  "\\LtwoRd": "L^2 \\rbk{\\bbR^d}",
  "\\LtwoRn": "L^2 \\rbk{\\bbR^n}",
  "\\LtwoS": "L^2 (S)",
  "\\LtwoXmu": "L^2 (X, \\mu)",
  "\\LtwoX": "L^2 (X)",
  "\\LtwoasbbRdN": "\\Ltwoas (\\bbRdN)",
  "\\Ltwoas": "L^2_{\\mathrm{as}}",
  "\\LtwobbRNkbkts": "\\langle #1,\\,#2 \\rangle_{\\LtwobbRNk}",
  "\\LtwobbRNkbkt": "\\left\\langle #1,\\,#2 \\right\\rangle_{\\LtwobbRNk}",
  "\\LtwobbRNknorms": "\\norms{#1}_{L^{2} (\\bbRNk)}",
  "\\LtwobbRNknorm": "\\norm{#1}_{L^{2} (\\bbRNk)}",
  "\\LtwobbRNk": "L^2 (\\bbRNk)",
  "\\LtwobbRNnorms": "\\norms{#1}_{L^{2} (\\bbRN)}",
  "\\LtwobbRNnorm": "\\norm{#1}_{L^{2} (\\bbRN)}",
  "\\LtwobbRNp": "L^2 (\\bbRNp)",
  "\\LtwobbRNxbkts": "\\langle #1,\\,#2 \\rangle_{\\LtwobbRNx}",
  "\\LtwobbRNxbkt": "\\left\\langle #1,\\,#2 \\right\\rangle_{\\LtwobbRNx}",
  "\\LtwobbRNxnorms": "\\norms{#1}_{L^{2} (\\bbRNx)}",
  "\\LtwobbRNxnorm": "\\norm{#1}_{L^{2} (\\bbRNx)}",
  "\\LtwobbRNx": "L^2 (\\bbRNx)",
  "\\LtwobbRNy": "L^2 (\\bbRNy)",
  "\\LtwobbRN": "L^2 (\\bbRN)",
  "\\LtwobbRdN": "L^2 (\\bbRdN)",
  "\\LtwobbRdkbkts": "\\langle #1,\\,#2 \\rangle_{\\LtwobbRdk}",
  "\\LtwobbRdkbkt": "\\left\\langle #1,\\,#2 \\right\\rangle_{\\LtwobbRdk}",
  "\\LtwobbRdknorms": "\\norms{#1}_{L^{2} (\\bbRdk)}",
  "\\LtwobbRdknorm": "\\norm{#1}_{L^{2} (\\bbRdk)}",
  "\\LtwobbRdk": "L^2 (\\bbRdk)",
  "\\LtwobbRdnorms": "\\norms{#1}_{L^{2} (\\bbRd)}",
  "\\LtwobbRdnorm": "\\norm{#1}_{L^{2} (\\bbRd)}",
  "\\LtwobbRdp": "L^2 (\\bbRdp)",
  "\\LtwobbRdxbkts": "\\langle #1,\\,#2 \\rangle_{\\LtwobbRdx}",
  "\\LtwobbRdxbkt": "\\left\\langle #1,\\,#2 \\right\\rangle_{\\LtwobbRdx}",
  "\\LtwobbRdxnorms": "\\norms{#1}_{L^{2} (\\bbRdx)}",
  "\\LtwobbRdxnorm": "\\norm{#1}_{L^{2} (\\bbRdx)}",
  "\\LtwobbRdx": "L^2 (\\bbRdx)",
  "\\LtwobbRdy": "L^2 (\\bbRdy)",
  "\\LtwobbRd": "L^2 (\\bbRd)",
  "\\LtwobbRm": "L^2 (\\bbRm)",
  "\\LtwobbRn": "L^2 (\\bbRn)",
  "\\LtwobbRthree": "L^2 (\\bbRthree)",
  "\\LtwobbR": "L^2 (\\bbR)",
  "\\Ltwoform": "L^2_{#1, #2}",
  "\\Ltwolimntoinfty": "L^2 \\myhyphen \\limntoinfty",
  "\\Ltwolim": "L^2 \\myhyphen \\lim",
  "\\LtwolocbbRN": "L^2_{\\mathrm{loc}} (\\bbRN)",
  "\\LtwolocbbRd": "L^2_{\\mathrm{loc}} (\\bbRd)",
  "\\Ltwolocform": "L^2_{\\mathrm{loc},#1,#2}",
  "\\Ltwoloc": "L^2_{\\mathrm{loc}}",
  "\\Ltwonorms": "\\norms{#1}_{\\Ltwo}",
  "\\Ltwonorm": "\\norm{#1}_{\\Ltwo}",
  "\\LtwopqOmegaphi": "\\Ltwopq (\\Omega, \\phi)",
  "\\Ltwopq": "L^2_{p,q}",
  "\\Ltworeal": "L^2_{\\mathrm{real}}",
  "\\LtwosbbRdN": "\\Ltwos (\\bbR^{dN})",
  "\\Ltwos": "L^2_{\\mathrm{s}}",
  "\\Ltwo": "L^2",
  "\\MX": "M (X)",
  "\\Map": "\\mathrm{Map}",
  "\\NcalM": "N_{\\calM}",
  "\\Nti": "N \\to \\infty",
  "\\OmegaAW": "\\Omega_{\\mathrm{AW}}",
  "\\Omegab": "\\Omega_{\\mathrm{b}}",
  "\\PSH": "\\mathrm{PSH}",
  "\\PcalH": "P (\\calH)",
  "\\Permutation": "{}_{#1} \\mathrm{P}_{#1}",
  "\\Pint": "\\mathrm{P} \\int",
  "\\Polydisc": "\\mathrm{P} \\triangle",
  "\\Rd": "\\mathbb{R}^{d}",
  "\\Ring": "\\mathsf{Ring}",
  "\\Rint": "\\mathrm{R} \\int",
  "\\Rtimes": "R^{\\times}",
  "\\SFplus": "\\mathrm{SF}_{\\geq 0}",
  "\\SF": "\\mathrm{SF}",
  "\\SH": "\\mathrm{SH}",
  "\\SPSH": "\\mathrm{SPSH}",
  "\\Sets": "\\mathsf{Sets}",
  "\\Top": "\\mathsf{Top}",
  "\\TrSuff": "\\Trace_{#1} \\sqbk{#2}",
  "\\Trsym": "\\Trace_{\\mathrm{sym}} \\sqbk{#1}",
  "\\Tr": "\\Trace \\sqbk{#1}",
  "\\Ualpha": "U_{\\alpha}",
  "\\Ubeta": "U_{\\beta}",
  "\\UcalH": "U (\\calH)",
  "\\Udel": "U^{\\mathrm{del}}",
  "\\Ulambda": "U_{\\lambda}",
  "\\Umu": "U_{\\mu}",
  "\\VC": "V_{\\mathrm{C}}",
  "\\Var": "\\mathrm{Var}\\sqbk{#1}",
  "\\VbbC": "V^{\\bbC}",
  "\\Wad": "W_{\\mathrm{ad}}",
  "\\WkpOmeganorms": "\\norms{#1}_{W^{k, p} (\\Omega)}",
  "\\WkpOmeganorm": "\\norm{#1}_{W^{k, p}}",
  "\\WkpOmega": "W^{k, p} (\\Omega)",
  "\\WkpbbRN": "W^{k, p} (\\bbRN)",
  "\\WkpbbRd": "W^{k, p} (\\bbRd)",
  "\\WkplocOmega": "W^{k, p}_{\\mathrm{loc}} (\\Omega)",
  "\\Wkploc": "W^{k, p}_{\\mathrm{loc}}",
  "\\WkpzeroOmega": "W^{k, p}_0 (\\Omega)",
  "\\Wkpzero": "W^{k, p}_0",
  "\\Wkp": "W^{k, p}",
  "\\WktwoOmega": "W^{k, 2} (\\Omega)",
  "\\Wktwo": "W^{k, 2}",
  "\\Wmax": "W_{\\mathrm{max}}",
  "\\WmpOmeganorms": "\\norms{#1}_{W^{m, p}}",
  "\\WmpOmeganorm": "\\norm{#1}_{W^{m, p}}",
  "\\WmpOmega": "W^{m, p} (\\Omega)",
  "\\WmpbbRN": "W^{m, p} (\\bbRN)",
  "\\WmpbbRd": "W^{m, p} (\\bbRd)",
  "\\WmpzeroOmega": "W^{m, p}_0 (\\Omega)",
  "\\Wmpzero": "W^{m, p}_0",
  "\\Wmp": "W^{m, p}",
  "\\WoneinftyOmega": "W^{1, \\infty} (\\Omega)",
  "\\WoneinftybbRN": "W^{1, \\infty} (\\bbRN)",
  "\\WoneinftybbRd": "W^{1, \\infty} (\\bbRd)",
  "\\WoneinftybbR": "W^{1, \\infty} (\\bbR)",
  "\\WoneoneOmega": "W^{1, 1} (\\Omega)",
  "\\WoneonebbR": "W^{1, 1} (\\bbR)",
  "\\WoneonelocOmega": "W^{1, 1}_{\\mathrm{loc}} (\\Omega)",
  "\\Woneoneloc": "W^{1, 1}_{\\mathrm{loc}}",
  "\\Woneonezero": "W_0^{1, 1}",
  "\\Woneone": "W^{1, 1}",
  "\\WonepOmeganorms": "\\norms{#1}_{W^{1, p} (\\Omega)}",
  "\\WonepOmeganorm": "\\norm{#1}_{W^{1, p} (\\Omega)}",
  "\\WonepOmega": "W^{1, p} (\\Omega)",
  "\\WonepbbRNnorms": "\\norms{#1}_{W^{1, p} (\\bbRN)}",
  "\\WonepbbRNnorm": "\\norm{#1}_{W^{1, p} (\\bbRN)}",
  "\\WonepbbRN": "W^{1, p} (\\bbRN)",
  "\\WonepbbRdnorms": "\\norms{#1}_{W^{1, p} (\\bbRd)}",
  "\\WonepbbRdnorm": "\\norm{#1}_{W^{1, p} (\\bbRd)}",
  "\\WonepbbRd": "W^{1, p} (\\bbRd)",
  "\\WonepbbR": "W^{1, p} (\\bbR)",
  "\\WoneplocOmega": "W^{1, p}_{\\mathrm{loc}} (\\Omega)",
  "\\Woneploc": "W^{1, p}_{\\mathrm{loc}}",
  "\\Wonepnorms": "\\norms{#1}_{W^{1, p}}",
  "\\Wonepnorm": "\\norm{#1}_{W^{1, p}}",
  "\\WoneponeOmega": "W^{1, 1}_{\\mathrm{loc}} (\\Omega)",
  "\\WoneponezeroOmega": "W_0^{1, 1}_{\\mathrm{loc}} (\\Omega)",
  "\\Woneponezero": "W_0^{1, 1}",
  "\\Wonepone": "W^{1, 1}",
  "\\WonepzeroOmega": "W_0^{1, p} (\\Omega)",
  "\\WonepzerobbRd": "W_0^{1, p} (\\bbRd)",
  "\\Wonepzero": "W_0^{1, p}",
  "\\Wonep": "W^{1, p}",
  "\\Woneq": "W^{1, q}",
  "\\WonerlocOmega": "W^{1, r}_{\\mathrm{loc}} (\\Omega)",
  "\\Wonerloc": "W^{1, r}_{\\mathrm{loc}}",
  "\\Wrhol": "W_{\\rho, \\mathrm{l}}",
  "\\Wstar": "W^{*}",
  "\\Zclbeta": "Z^{\\mathrm{cl}}_{\\beta}",
  "\\Zcl": "Z^{\\mathrm{cl}}",
  "\\aaadjoint": "#1^{***}",
  "\\aadjointA": "\\aadjoint{A}",
  "\\aadjoint": "#1^{**}",
  "\\absfrac": "\\left| \\frac{#1}{#2} \\right|",
  "\\absmu": "\\abs{\\mu}",
  "\\absnu": "\\abs{\\nu}",
  "\\absolutelyContinuousSpectrumH": "\\sigma_{\\rmac} \\rbk{H}",
  "\\absolutelyContinuousSpectrum": "\\sigma_{\\rmac} \\rbk{#1}",
  "\\absszti": "\\abss{z} \\to \\infty",
  "\\abss": "| #1 |",
  "\\abs": "\\left|#1\\right|",
  "\\adjointAA": "\\adjoint{A}A",
  "\\adjointA": "\\adjoint{A}",
  "\\adjointB": "\\adjoint{B}",
  "\\adjointUU": "\\adjoint{U}U",
  "\\adjointU": "\\adjoint{U}",
  "\\adjointVV": "\\adjoint{V}V",
  "\\adjointV": "\\adjoint{V}",
  "\\adjoint": "#1^{*}",
  "\\aia": "\\alpha \\in A",
  "\\an": "(a_n)_{n{\\in}{\\bN}}",
  "\\approximatePointSpectrumA": "\\sigma_{\\mathrm{ap}} \\rbk{A}",
  "\\approximatePointSpectrum": "\\sigma_{\\mathrm{ap}} \\rbk{#1}",
  "\\asbigtensor": "\\bigotimes_{\\mathrm{as}}",
  "\\astensor": "\\otimes_{\\mathrm{as}}",
  "\\bB": "\\mathbb{B}",
  "\\bC": "\\mathbb{C}",
  "\\bN": "\\mathbb{N}",
  "\\bQ": "\\mathbb{Q}",
  "\\bR": "\\mathbb{R}",
  "\\barstar": "\\bar{\\star}",
  "\\basebk": "\\dbk{#1}",
  "\\basebkiI": "\\basebk{#1_i}_{i \\in I}",
  "\\basebkkI": "\\basebk{#1_k}_{k \\in I}",
  "\\baseiin": "\\dbk{#1_i}_{i=1}^{#2}",
  "\\basei": "\\dbk{#1_i}_{i=1}^{#2}",
  "\\basekonetod": "\\dbk{#1_k}_{k=1}^{d}",
  "\\basekoneton": "\\dbk{#1_k}_{k=1}^{n}",
  "\\baselam": "\\base{#1_{\\lambda}}{\\lil}",
  "\\basem": "\\dbk{#1_k}_{k=1}^{m}",
  "\\basenonetoN": "\\dbk{#1_n}_{\\nin}",
  "\\basenone": "\\dbk{#1_n}_{\\ninone}",
  "\\basen": "\\dbk{#1_n}_{\\nin}",
  "\\base": "\\dbk{#1}_{#2}",
  "\\bbAn": "\\mathbb{A}^n",
  "\\bbA": "\\mathbb{A}",
  "\\bbBcalH": "\\mathbb{B} (\\calH)",
  "\\bbBcalK": "\\mathbb{B} (\\calK)",
  "\\bbB": "\\mathbb{B}",
  "\\bbCN": "\\bbC^N",
  "\\bbCP": "\\bbC \\bbP^{#1}",
  "\\bbCd": "\\mathbb{C}^d",
  "\\bbCg": "\\mathbb{C}^g",
  "\\bbCk": "\\mathbb{C}^k",
  "\\bbCm": "\\mathbb{C}^m",
  "\\bbCn": "\\mathbb{C}^n",
  "\\bbCp": "\\mathbb{C}^p",
  "\\bbCq": "\\mathbb{C}^q",
  "\\bbCr": "\\mathbb{C}^r",
  "\\bbCtimes": "\\mathbb{C}^{\\times}",
  "\\bbCthree": "\\mathbb{C}^3",
  "\\bbCtwo": "\\mathbb{C}^2",
  "\\bbC": "\\mathbb{C}",
  "\\bbD": "\\mathbb{D}",
  "\\bbEd": "\\mathbb{E}^d",
  "\\bbEm": "\\mathbb{E}^m",
  "\\bbEn": "\\mathbb{E}^n",
  "\\bbE": "\\mathbb{E}",
  "\\bbFcalH": "\\mathbb{F} (\\calH)",
  "\\bbF": "\\mathbb{F}",
  "\\bbG": "\\mathbb{G}",
  "\\bbHk": "\\mathbb{H}^k",
  "\\bbHm": "\\mathbb{H}^m",
  "\\bbHn": "\\mathbb{H}^n",
  "\\bbH": "\\mathbb{H}",
  "\\bbI": "\\mathbb{I}",
  "\\bbJ": "\\mathbb{J}",
  "\\bbKcalH": "\\mathbb{K} (\\calH)",
  "\\bbKd": "\\mathbb{K}^d",
  "\\bbKfincalH": "\\mathbb{K}_{\\mathrm{fin}} (\\calH)",
  "\\bbKm": "\\mathbb{K}^m",
  "\\bbKn": "\\mathbb{K}^n",
  "\\bbKr": "\\mathbb{K}^r",
  "\\bbK": "\\mathbb{K}",
  "\\bbL": "\\mathbb{L}",
  "\\bbMbddnn": "\\mathbb{M}_{\\rm{b}, \\geq}",
  "\\bbMbdd": "\\mathbb{M}_{\\rm{b}}",
  "\\bbMd": "\\mathbb{M}^d",
  "\\bbMfour": "\\mathbb{M}^4",
  "\\bbMnn": "\\mathbb{M}_{\\geq 0}",
  "\\bbM": "\\mathbb{M}",
  "\\bbNN": "\\mathbb{N}^N",
  "\\bbNcpt": "\\cpt{\\mathbb{N}}",
  "\\bbNd": "\\mathbb{N}^d",
  "\\bbNm": "\\mathbb{N}^m",
  "\\bbNn": "\\mathbb{N}^n",
  "\\bbNone": "\\mathbb{N}_1",
  "\\bbNzero": "\\mathbb{N}_0",
  "\\bbN": "\\mathbb{N}",
  "\\bbO": "\\mathbb{O}",
  "\\bbPC": "\\mathbb{P}^{#1} (\\bbC)",
  "\\bbPR": "\\mathbb{P}^{#1} (\\bbR)",
  "\\bbPcalH": "\\bbP (\\calH)",
  "\\bbPk": "\\mathbb{P}^{#1} (k)",
  "\\bbPmraC": "\\mathbb{P}^{m} (\\bbC)",
  "\\bbPmR": "\\mathbb{P}^{m} (\\bbR)",
  "\\bbPmk": "\\mathbb{P}^m (k)",
  "\\bbPm": "\\mathbb{P}^m",
  "\\bbPmC": "\\mathbb{P}^{m} (\\bbC)",
  "\\bbPnC": "\\mathbb{P}^{n} (\\bbC)",
  "\\bbPnR": "\\mathbb{P}^{n} (\\bbR)",
  "\\bbPnk": "\\mathbb{P}^n (k)",
  "\\bbPn": "\\mathbb{P}^n",
  "\\bbPonebbC": "\\mathbb{P}^1 (\\bbC)",
  "\\bbPonebbR": "\\mathbb{P}^1 (\\bbR)",
  "\\bbPone": "\\mathbb{P}^1",
  "\\bbP": "\\mathbb{P}",
  "\\bbQd": "\\mathbb{Q}^d",
  "\\bbQp": "\\mathbb{Q}_{p}",
  "\\bbQtimes": "\\mathbb{Q}^{\\times}",
  "\\bbQ": "\\mathbb{Q}",
  "\\bbRNplus": "\\mathbb{R}^N_{>0}",
  "\\bbRNp": "\\mathbb{R}_p^N",
  "\\bbRNx": "\\mathbb{R}_x^N",
  "\\bbRNy": "\\mathbb{R}_y^N",
  "\\bbRN": "\\mathbb{R}^N",
  "\\bbRPn": "\\bbR \\bbP^n",
  "\\bbRP": "\\bbR \\bbP^{#1}",
  "\\bbRbar": "\\bar{\\mathbb{R}}",
  "\\bbRbbN": "\\mathbb{R}^{\\bbN}",
  "\\bbRcptbbNone": "\\cpt{\\mathbb{R}}^{\\bbNone}",
  "\\bbRcptbbN": "\\cpt{\\mathbb{R}}^{\\bbN}",
  "\\bbRcptd": "\\cpt{\\mathbb{R}}^d",
  "\\bbRcpt": "\\cpt{\\mathbb{R}}",
  "\\bbRdN": "\\mathbb{R}^{dN}",
  "\\bbRdk": "\\mathbb{R}_k^d",
  "\\bbRdn": "\\mathbb{R}^{dn}",
  "\\bbRdplus": "\\mathbb{R}^d_{>0}",
  "\\bbRdp": "\\mathbb{R}_p^d",
  "\\bbRdx": "\\mathbb{R}_x^d",
  "\\bbRdy": "\\mathbb{R}_y^d",
  "\\bbRd": "\\mathbb{R}^d",
  "\\bbRfour": "\\mathbb{R}^4",
  "\\bbRinfty": "\\mathbb{R}^{\\infty}",
  "\\bbRk": "\\mathbb{R}^k",
  "\\bbRmnonnegative": "\\mathbb{R}^m_{\\geq 0}",
  "\\bbRmplusone": "\\mathbb{R}^{m+1}",
  "\\bbRmplus": "\\mathbb{R}^m_{> 0}",
  "\\bbRm": "\\mathbb{R}^m",
  "\\bbRnn": "\\mathbb{R}_{\\geq 0}",
  "\\bbRnonnegative": "\\mathbb{R}_{\\geq 0}",
  "\\bbRnplusone": "\\mathbb{R}^{n+1}",
  "\\bbRnp": "\\mathbb{R}_{\\leq 0}",
  "\\bbRnu": "\\mathbb{R}^{\\nu}",
  "\\bbRn": "\\mathbb{R}^n",
  "\\bbRplusup": "\\mathbb{R}^{> 0}",
  "\\bbRplus": "\\mathbb{R}_{> 0}",
  "\\bbRone": "\\mathbb{R}^1",
  "\\bbRp": "\\mathbb{R}^p",
  "\\bbRq": "\\mathbb{R}^q",
  "\\bbRr": "\\mathbb{R}^r",
  "\\bbRsubk": "\\mathbb{R}_k",
  "\\bbRthreeN": "\\mathbb{R}^{3N}",
  "\\bbRthreek": "\\mathbb{R}^3_k",
  "\\bbRthreex": "\\mathbb{R}^3_x",
  "\\bbRthree": "\\mathbb{R}^3",
  "\\bbRtimes": "\\mathbb{R}^\\times",
  "\\bbRtwo": "\\mathbb{R}^2",
  "\\bbRx": "\\mathbb{R}_x",
  "\\bbR": "\\mathbb{R}",
  "\\bbS": "\\mathbb{S}",
  "\\bbT": "\\mathbb{T}",
  "\\bbTm": "\\mathbb{T}^m",
  "\\bbTn": "\\mathbb{T}^n",
  "\\bbUcalH": "\\bbU (\\calH)",
  "\\bbU": "\\mathbb{U}",
  "\\bbV": "\\mathbb{V}",
  "\\bbW": "\\mathbb{W}",
  "\\bbX": "\\mathbb{X}",
  "\\bbY": "\\mathbb{Y}",
  "\\bbZd": "\\mathbb{Z}^d",
  "\\bbZnonnegative": "\\mathbb{Z}_{\\geq 0}",
  "\\bbZn": "\\mathbb{Z}^n",
  "\\bbZplus": "\\mathbb{Z}_{>0}",
  "\\bbZp": "\\mathbb{Z}_{> 0}",
  "\\bbZ": "\\mathbb{Z}",
  "\\bba": "\\mathbb{a}",
  "\\bbb": "\\mathbb{b}",
  "\\bbc": "\\mathbb{c}",
  "\\bbd": "\\mathbb{d}",
  "\\bbe": "\\mathbb{e}",
  "\\bbf": "\\mathbb{f}",
  "\\bbg": "\\mathbb{g}",
  "\\bbh": "\\mathbb{h}",
  "\\bbi": "\\mathbb{i}",
  "\\bbj": "\\mathbb{j}",
  "\\bbk": "\\mathbb{k}",
  "\\bbl": "\\mathbb{l}",
  "\\bbm": "\\mathbb{m}",
  "\\bbn": "\\mathbb{n}",
  "\\bbone": "\\mathbbm{1}",
  "\\bbo": "\\mathbb{o}",
  "\\bbp": "\\mathbb{p}",
  "\\bbq": "\\mathbb{q}",
  "\\bbr": "\\mathbb{r}",
  "\\bbs": "\\mathbb{s}",
  "\\bbt": "\\mathbb{t}",
  "\\bbu": "\\mathbb{u}",
  "\\bbv": "\\mathbb{v}",
  "\\bbw": "\\mathbb{w}",
  "\\bbx": "\\mathbb{x}",
  "\\bby": "\\mathbb{y}",
  "\\bbz": "\\mathbb{z}",
  "\\bddopH": "\\bbB (\\calH)",
  "\\bddopK": "\\bbB (\\calK)",
  "\\betac": "\\beta_{\\mathrm{c}}",
  "\\bfA": "\\mathbf{A}",
  "\\bfB": "\\mathbf{B}",
  "\\bfC": "\\mathbf{C}",
  "\\bfD": "\\mathbf{D}",
  "\\bfE": "\\mathbf{E}",
  "\\bfF": "\\mathbf{F}",
  "\\bfG": "\\mathbf{G}",
  "\\bfH": "\\mathbf{H}",
  "\\bfI": "\\mathbf{I}",
  "\\bfJ": "\\mathbf{J}",
  "\\bfK": "\\mathbf{K}",
  "\\bfL": "\\mathbf{L}",
  "\\bfM": "\\mathbf{M}",
  "\\bfN": "\\mathbf{N}",
  "\\bfO": "\\mathbf{O}",
  "\\bfP": "\\mathbf{P}",
  "\\bfQ": "\\mathbf{Q}",
  "\\bfR": "\\mathbf{R}",
  "\\bfS": "\\mathbf{S}",
  "\\bfT": "\\mathbf{T}",
  "\\bfU": "\\mathbf{U}",
  "\\bfV": "\\mathbf{V}",
  "\\bfW": "\\mathbf{W}",
  "\\bfX": "\\mathbf{X}",
  "\\bfY": "\\mathbf{Y}",
  "\\bfZ": "\\mathbf{Z}",
  "\\bfa": "\\mathbf{a}",
  "\\bfb": "\\mathbf{b}",
  "\\bfc": "\\mathbf{c}",
  "\\bfd": "\\mathbf{d}",
  "\\bfe": "\\mathbf{e}",
  "\\bff": "\\mathbf{f}",
  "\\bfg": "\\mathbf{g}",
  "\\bfh": "\\mathbf{h}",
  "\\bfi": "\\mathbf{i}",
  "\\bfj": "\\mathbf{j}",
  "\\bfk": "\\mathbf{k}",
  "\\bfl": "\\mathbf{l}",
  "\\bfm": "\\mathbf{m}",
  "\\bfn": "\\mathbf{n}",
  "\\bfo": "\\mathbf{o}",
  "\\bfp": "\\mathbf{p}",
  "\\bfq": "\\mathbf{q}",
  "\\bfr": "\\mathbf{r}",
  "\\bfs": "\\mathbf{s}",
  "\\bft": "\\mathbf{t}",
  "\\bfu": "\\mathbf{u}",
  "\\bfv": "\\mathbf{v}",
  "\\bfw": "\\mathbf{w}",
  "\\bfx": "\\mathbf{x}",
  "\\bfy": "\\mathbf{y}",
  "\\bfz": "\\mathbf{z}",
  "\\bigcapkin": "\\bigcap_{\\kin} #1",
  "\\bigcapknonein": "\\bigcap_{\\kinone} #1",
  "\\bigcapknone": "\\bigcap_{\\kinone} #1_{k}",
  "\\bigcapk": "\\bigcap_{\\kin} #1_{k}",
  "\\bigcaplamin": "\\bigcap_{\\lil} #1",
  "\\bigcaplam": "\\bigcap_{\\lil} #1_{\\lambda}",
  "\\bigcapnin": "\\bigcap_{\\nin} #1",
  "\\bigcapnonein": "\\bigcap_{\\ninone} #1",
  "\\bigcapnone": "\\bigcap_{\\ninone} #1_{n}",
  "\\bigcapn": "\\bigcap_{\\nin} #1_{n}",
  "\\bigcupkinonein": "\\bigcup_{\\kinone} #1",
  "\\bigcupkinone": "\\bigcup_{\\kinone} #1_{k}",
  "\\bigcupkin": "\\bigcup_{\\kin} #1",
  "\\bigcupk": "\\bigcup_{\\kin} #1_{k}",
  "\\bigcuplamin": "\\bigcup_{\\lil} #1",
  "\\bigcuplam": "\\bigcup_{\\lil} #1_{\\lambda}",
  "\\bigcupnin": "\\bigcup_{\\nin} #1",
  "\\bigcupnonein": "\\bigcup_{\\ninone} #1",
  "\\bigcupnone": "\\bigcup_{\\ninone} #1_{n}",
  "\\bigcupn": "\\bigcup_{\\nin} #1_{n}",
  "\\bigdbk": "\\big\\left\\langle #1 \\big\\right\\rangle",
  "\\bigrbk": "\\big( #1 \\big)",
  "\\bigslash": "\\left. #1 \\middle/ #2 \\right.",
  "\\bkts": "\\langle #1,\\,#2 \\rangle",
  "\\bktvert": "\\left\\langle #1 \\vert #2 \\right\\rangle",
  "\\bkt": "\\left\\langle #1,\\,#2 \\right\\rangle",
  "\\bn": "(b_n)_{n{\\in}{\\bN}}",
  "\\boldA": "\\boldsymbol{A}",
  "\\boldB": "\\boldsymbol{B}",
  "\\boldC": "\\boldsymbol{C}",
  "\\boldD": "\\boldsymbol{D}",
  "\\boldE": "\\boldsymbol{E}",
  "\\boldF": "\\boldsymbol{F}",
  "\\boldG": "\\boldsymbol{G}",
  "\\boldH": "\\boldsymbol{H}",
  "\\boldI": "\\boldsymbol{I}",
  "\\boldJ": "\\boldsymbol{J}",
  "\\boldK": "\\boldsymbol{K}",
  "\\boldL": "\\boldsymbol{L}",
  "\\boldM": "\\boldsymbol{M}",
  "\\boldN": "\\boldsymbol{N}",
  "\\boldO": "\\boldsymbol{O}",
  "\\boldP": "\\boldsymbol{P}",
  "\\boldQ": "\\boldsymbol{Q}",
  "\\boldR": "\\boldsymbol{R}",
  "\\boldS": "\\boldsymbol{S}",
  "\\boldT": "\\boldsymbol{T}",
  "\\boldU": "\\boldsymbol{U}",
  "\\boldV": "\\boldsymbol{V}",
  "\\boldW": "\\boldsymbol{W}",
  "\\boldX": "\\boldsymbol{X}",
  "\\boldY": "\\boldsymbol{Y}",
  "\\boldZ": "\\boldsymbol{Z}",
  "\\bolda": "\\boldsymbol{a}",
  "\\boldb": "\\boldsymbol{b}",
  "\\boldc": "\\boldsymbol{c}",
  "\\boldd": "\\boldsymbol{d}",
  "\\bolde": "\\boldsymbol{e}",
  "\\boldf": "\\boldsymbol{f}",
  "\\boldg": "\\boldsymbol{g}",
  "\\boldh": "\\boldsymbol{h}",
  "\\boldi": "\\boldsymbol{i}",
  "\\boldj": "\\boldsymbol{j}",
  "\\boldk": "\\boldsymbol{k}",
  "\\boldl": "\\boldsymbol{l}",
  "\\boldlambda": "\\boldsymbol{\\lambda}",
  "\\boldm": "\\boldsymbol{m}",
  "\\boldn": "\\boldsymbol{n}",
  "\\boldone": "\\boldsymbol{1}",
  "\\boldo": "\\boldsymbol{o}",
  "\\boldp": "\\boldsymbol{p}",
  "\\boldq": "\\boldsymbol{q}",
  "\\boldr": "\\boldsymbol{r}",
  "\\bolds": "\\boldsymbol{s}",
  "\\boldsigma": "\\boldsymbol{\\sigma}",
  "\\boldt": "\\boldsymbol{t}",
  "\\boldu": "\\boldsymbol{u}",
  "\\boldv": "\\boldsymbol{v}",
  "\\boldw": "\\boldsymbol{w}",
  "\\boldx": "\\boldsymbol{x}",
  "\\boldy": "\\boldsymbol{y}",
  "\\boldz": "\\boldsymbol{z}",
  "\\brakets": "\\langle #1 | #2 \\rangle",
  "\\braket": "\\left\\langle #1 \\middle| #2 \\right\\rangle",
  "\\bra": "\\left\\langle #1 \\right|",
  "\\calAplus": "\\mathcal{A}_+",
  "\\calA": "\\mathcal{A}",
  "\\calBbbN": "\\mathcal{B}^{\\bbN}",
  "\\calBdn": "\\mathcal{B}^{dn}",
  "\\calBd": "\\mathcal{B}^d",
  "\\calBext": "\\ext{\\mathcal{B}}",
  "\\calB": "\\mathcal{B}",
  "\\calCN": "\\mathcal{C}_{N}",
  "\\calCfinH": "\\mathcal{C}_{\\mathrm{fin}} (\\calH)",
  "\\calCinfty": "\\mathcal{C}^{\\infty}",
  "\\calCleqN": "\\mathcal{C}_{\\leq N}",
  "\\calCps": "\\calC^{\\mathrm{ps}}",
  "\\calC": "\\mathcal{C}",
  "\\calDOmega": "\\mathcal{D} (\\Omega)",
  "\\calDbbRN": "\\mathcal{D} (\\bbRN)",
  "\\calDbbRd": "\\mathcal{D} (\\bbRd)",
  "\\calD": "\\mathcal{D}",
  "\\calEd": "\\mathcal{E}^d",
  "\\calE": "\\mathcal{E}",
  "\\calFAW": "\\calF_{\\mathrm{AW}}",
  "\\calFas": "\\mathcal{F}_{\\mathrm{as}}",
  "\\calFbAW": "\\calF_{\\mathrm{b,ArakiWoods}}",
  "\\calFbcalH": "\\mathcal{F}_{\\mathrm{b}} (\\calH)",
  "\\calFbfin": "\\mathcal{F}_{\\mathrm{b,fin}}",
  "\\calFbzero": "\\mathcal{F}_{\\mathrm{b,0}}",
  "\\calFb": "\\mathcal{F}_{\\mathrm{b}}",
  "\\calFcalH": "\\calF (\\calH)",
  "\\calFel": "\\calF_{\\mathrm{el}}",
  "\\calFfAW": "\\calF_{\\mathrm{f,ArakiWyss}}",
  "\\calFffin": "\\mathcal{F}_{\\mathrm{f,fin}}",
  "\\calFfin": "\\mathcal{F}_{\\mathrm{fin}}",
  "\\calFfzero": "\\mathcal{F}_{\\mathrm{f,0}}",
  "\\calFf": "\\mathcal{F}_{\\mathrm{f}}",
  "\\calFh": "\\calF_{\\mathrm{h}}",
  "\\calFmuLouter": "\\mathcal{F}_{\\muLouter}",
  "\\calFmuouter": "\\mathcal{F}_{\\muouter}",
  "\\calFmu": "\\mathcal{F}_{\\mu}",
  "\\calFs": "\\mathcal{F}_{\\mathrm{s}}",
  "\\calF": "\\mathcal{F}",
  "\\calG": "\\mathcal{G}",
  "\\calHac": "\\calH_{\\mathrm{ac}}",
  "\\calHbkts": "\\langle #1,\\,#2 \\rangle_{\\calH}",
  "\\calHbkt": "\\left\\langle #1,\\,#2 \\right\\rangle_{\\calH}",
  "\\calHs": "\\calH_{\\mathrm{s}}",
  "\\calH": "\\mathcal{H}",
  "\\calIb": "\\mathcal{I}_{\\mathrm{b}}",
  "\\calId": "\\mathcal{I}^d",
  "\\calI": "\\mathcal{I}",
  "\\calJ": "\\mathcal{J}",
  "\\calKbkts": "\\langle #1,\\,#2 \\rangle_{\\calK}",
  "\\calKbkt": "\\left\\langle #1,\\,#2 \\right\\rangle_{\\calK}",
  "\\calKfinH": "\\mathcal{K}_{\\mathrm{fin}} (\\calH)",
  "\\calK": "\\mathcal{K}",
  "\\calLploc": "\\mathcal{L}^p_{\\mathrm{loc}}",
  "\\calLp": "\\mathcal{L}^p",
  "\\calL": "\\mathcal{L}",
  "\\calMd": "\\mathcal{M}^d",
  "\\calMplus": "\\mathcal{M}_*",
  "\\calM": "\\mathcal{M}",
  "\\calN": "\\mathcal{N}",
  "\\calOtimes": "\\mathcal{O}^{\\times}",
  "\\calOwstar": "\\mathcal{O}_{\\rmw^{*}}",
  "\\calOw": "\\mathcal{O}_{\\rmw}",
  "\\calO": "\\mathcal{O}",
  "\\calP": "\\mathcal{P}",
  "\\calQ": "\\mathcal{Q}",
  "\\calRd": "\\mathcal{R}^d",
  "\\calR": "\\mathcal{R}",
  "\\calSbbRNk": "\\mathcal{S} (\\bbRNk)",
  "\\calSbbRNx": "\\mathcal{S} (\\bbRNx)",
  "\\calSbbRN": "\\mathcal{S} (\\bbRN)",
  "\\calSbbRdk": "\\mathcal{S} (\\bbRdk)",
  "\\calSbbRdx": "\\mathcal{S} (\\bbRdx)",
  "\\calSbbRd": "\\mathcal{S} (\\bbRd)",
  "\\calSbbRn": "\\mathcal{S} (\\bbRn)",
  "\\calSbbR": "\\mathcal{S} (\\bbR)",
  "\\calS": "\\mathcal{S}",
  "\\calT": "\\mathcal{T}",
  "\\calUbbR": "\\calU(\\bbR)",
  "\\calUnsbbR": "\\calU(\\nsbbR)",
  "\\calU": "\\mathcal{U}",
  "\\calV": "\\mathcal{V}",
  "\\calW": "\\mathcal{W}",
  "\\calX": "\\mathcal{X}",
  "\\calY": "\\mathcal{Y}",
  "\\calZ": "\\mathcal{Z}",
  "\\catT": "\\mathrm{T}",
  "\\cbks": "\\{ #1 \\}",
  "\\cbk": "\\left\\{ #1 \\right\\}",
  "\\cech": "\\check{\\mathrm{H}}",
  "\\ceilfunc": "\\lceil #1 \\rceil",
  "\\celcius": "{}^\\circ\\mathrm{C}",
  "\\charset": "\\chi_{\\cbk{#1}}",
  "\\chb": "\\mathrm{Ch}^{\\mathrm{b}}",
  "\\chminus": "\\mathrm{Ch}^{-}",
  "\\chnonnegative": "\\mathrm{Ch}^{\\geq 0}",
  "\\chplus": "\\mathrm{Ch}^{+}",
  "\\closureA": "\\closure{A}",
  "\\closureB": "\\closure{B}",
  "\\closure": "\\overline{#1}",
  "\\coho": "\\mathrm{H}",
  "\\coloredtextbf": "\\textbf{\\textcolor{blue}{#1}}",
  "\\comb": "\\begin{pmatrix} #1 \\\\ #2 \\end{pmatrix}",
  "\\complexcotangentspace": "T_{#1}^{* \\bbC} #2",
  "\\complextangentspace": "T_{#1}^{\\bbC} #2",
  "\\conjI": "\\overline{I}",
  "\\conjJ": "\\overline{J}",
  "\\conjalpha": "\\overline{\\alpha}",
  "\\conjbeta": "\\overline{\\beta}",
  "\\conji": "\\overline{i}",
  "\\conjj": "\\overline{j}",
  "\\conjk": "\\overline{k}",
  "\\conjugatealpha": "\\overline{\\alpha}",
  "\\conjugatebeta": "\\overline{\\beta}",
  "\\conjugatew": "\\overline{w}",
  "\\conjugatez": "\\overline{z}",
  "\\conjugate": "\\overline{#1}",
  "\\conjw": "\\overline{w}",
  "\\conjzeta": "\\overline{\\zeta}",
  "\\conjz": "\\overline{z}",
  "\\conj": "\\overline{#1}",
  "\\const": "\\mathrm{const}",
  "\\continuousSpectrumA": "\\sigma_{\\mathrm{c}} \\rbk{A}",
  "\\continuousSpectrum": "\\sigma_{\\mathrm{c}} \\rbk{#1}",
  "\\cotangentspace": "T_{#1}^* #2",
  "\\cotbdleM": "\\cotbdle{M}",
  "\\cotbdleN": "\\cotbdle{N}",
  "\\cotbdle": "T^* #1",
  "\\cotspM": "T_{#1}^* M",
  "\\cotspN": "T_{#1}^* N",
  "\\cotsp": "T_{#1}^* #2",
  "\\cpt": "\\dot{#1}",
  "\\dAlembertian": "\\Box",
  "\\dA": "\\, dA",
  "\\dElambda": "\\, dE (\\lambda)",
  "\\dEx": "\\, dE(x)",
  "\\dE": "\\, dE",
  "\\dF": "\\, dF",
  "\\dGammab": "d \\Gamma_{\\mathrm{b}}",
  "\\dGammaf": "d \\Gamma_{\\mathrm{f}}",
  "\\dGamma": "d \\Gamma",
  "\\dG": "\\, dG",
  "\\dP": "\\, dP",
  "\\dQ": "\\, dQ",
  "\\dS": "\\, dS",
  "\\dV": "\\, dV",
  "\\dX": "\\, dX",
  "\\dabsmu": "\\, d \\absmu",
  "\\dalpha": "\\partial^{\\alpha}",
  "\\da": "\\, da",
  "\\dbarEsharp": "\\dbar^{E \\#}",
  "\\dbarE": "\\dbar^E",
  "\\dbarsharp": "\\dbar^{\\#}",
  "\\dbar": "\\conjugate{\\partial}",
  "\\dbkjd": "\\dbk{#1_j}_{j=1}^d",
  "\\dbkjm": "\\dbk{#1_j}_{j=1}^m",
  "\\dbkjnone": "\\dbk{#1_j}_{j \\in \\bbNone}",
  "\\dbkjn": "\\dbk{#1_j}_{j=1}^n",
  "\\dbkmnone": "\\dbk{#1_m}_{m \\in \\bbNone}",
  "\\dbknnone": "\\dbk{#1_n}_{\\ninone}",
  "\\dbks": "\\langle #1 \\rangle",
  "\\dbkts": "\\, d \\bkts{#1}{#2}",
  "\\dbkt": "\\, d \\bkt{#1}{#2}",
  "\\dbk": "\\left\\langle #1 \\right\\rangle",
  "\\db": "\\, db",
  "\\dconjugatew": "\\, d \\conjugatew",
  "\\dconjugatez": "\\, d \\conjugatez",
  "\\dconjw": "\\, d \\conjw",
  "\\dconjz": "\\, d \\conjz",
  "\\dc": "\\, dc",
  "\\dddualX": "\\dddual{X}",
  "\\dddual": "#1^{***}",
  "\\ddsop": "\\frac{d #1}{ds}",
  "\\dds": "\\frac{d}{ds}",
  "\\ddtop": "\\frac{d #1}{dt}",
  "\\ddt": "\\frac{d}{dt}",
  "\\ddualX": "\\ddual{X}",
  "\\ddual": "#1^{**}",
  "\\degC": "{}^\\circ \\mathrm{C}",
  "\\deltat": "\\varDelta t",
  "\\del": "\\varDelta",
  "\\deta": "\\, d \\eta",
  "\\dftovfbk": "\\rbk{#1}^{\\sharp}",
  "\\dftovfone": "#1^{\\sharp_1}",
  "\\dftovftwo": "#1^{\\sharp_1}",
  "\\dftovf": "#1^{\\sharp}",
  "\\df": "\\, df",
  "\\dgb": "d\\Gamma_{\\mathrm{b}}",
  "\\dge": "d\\Gamma_{\\mathrm{e}}",
  "\\dg": "\\, dg",
  "\\diffformspace": "\\Omega",
  "\\discreteSpectrumA": "\\sigma_{\\mathrm{d}} \\rbk{A}",
  "\\discreteSpectrum": "\\sigma_{\\mathrm{d}} \\rbk{#1}",
  "\\distinfty": "d_{\\infty}",
  "\\distone": "d_{1}",
  "\\distp": "d_{p}",
  "\\distributionOmega": "\\dual{\\calD (\\Omega)}",
  "\\distributionbbRN": "\\dual{\\calD (\\bbRN)}",
  "\\distributionbbRd": "\\dual{\\calD (\\bbRd)}",
  "\\distributionbbR": "\\dual{\\calD (\\bbR)}",
  "\\disttwo": "d_{2}",
  "\\divergencedotinpr": "\\dotinpr{\\nabla}{#1}",
  "\\dk": "\\, dk",
  "\\dlambda": "\\, d \\lambda",
  "\\dl": "\\, dl",
  "\\dmuLoebx": "\\, d \\muLoeb (x)",
  "\\dmuLoeby": "\\, d \\muLoeb (y)",
  "\\dmuLoeb": "\\, d \\muLoeb",
  "\\dmuLx": "\\, d \\muL (x)",
  "\\dmuLy": "\\, d \\muL (y)",
  "\\dmuL": "\\, d \\muL",
  "\\dmux": "\\, d \\mu (x)",
  "\\dmuy": "\\, d \\mu (y)",
  "\\dmuzero": "\\, d \\muzero",
  "\\dmu": "\\, d \\mu",
  "\\dmynvec": "\\, d \\mynvec{#1}{#2}",
  "\\dnorms": "\\, d \\norms{#1}",
  "\\dnorm": "\\, d \\norm{#1}",
  "\\dnux": "\\, d \\nu (x)",
  "\\dnuy": "\\, d \\nu (y)",
  "\\dnu": "\\, d \\nu",
  "\\domega": "\\, d \\omega",
  "\\dotinpr": "#1 \\cdot #2",
  "\\dotgamma": "\\dot{\\gamma}",
  "\\doublecbks": "\\cbk{\\cbk{#1}}",
  "\\doubletilde": "\\tilde{\\tilde{#1}}",
  "\\dphi": "\\, d \\phi",
  "\\drho": "\\, d \\rho",
  "\\dr": "\\, dr",
  "\\dsharp": "\\partial^{\\#}",
  "\\dsigma": "\\, d \\sigma",
  "\\ds": "\\, ds",
  "\\dtau": "\\, d \\tau",
  "\\dtheta": "\\, d \\theta",
  "\\dt": "\\, dt",
  "\\dualA": "\\dual{A}",
  "\\dualX": "\\dual{X}",
  "\\dualfrakh": "\\dual{\\frakh}",
  "\\dualnabla": "\\dual{\\nabla}",
  "\\dual": "#1^{*}",
  "\\du": "\\, du",
  "\\dvol": "\\, d \\vol",
  "\\dv": "\\, dv",
  "\\dw": "\\, dw",
  "\\dxi": "\\, d \\xi",
  "\\dx": "\\, dx",
  "\\dy": "\\, dy",
  "\\dzeta": "\\, d \\zeta",
  "\\dz": "\\, dz",
  "\\eitheta": "e^{\\itheta}",
  "\\ellinfty": "\\ell^{\\infty}",
  "\\ellone": "\\ell^1",
  "\\ellp": "\\ell^p",
  "\\ellq": "\\ell^q",
  "\\elltwo": "\\ell^2",
  "\\eminusbeta": "e^{-\\beta #1}",
  "\\eminust": "e^{-t #1}",
  "\\etaone": "\\setSymbolDownLeft{1}{\\eta}",
  "\\etaonerbkt": "\\setSymbolDownLeft{1}{\\eta} \\rbkt{#1}{#2}",
  "\\etatwo": "\\setSymbolDownLeft{2}{\\eta}",
  "\\etatworbkt": "\\setSymbolDownLeft{2}{\\eta} \\rbkt{#1}{#2}",
  "\\epsilonN": "\\ep \\myhyphen N",
  "\\epsilondelta": "\\ep \\myhyphen \\delta",
  "\\ep": "\\varepsilon",
  "\\eqcls": "\\sqbk{#1}",
  "\\eqc": "\\overline{#1}} % equivalence clas",
  "\\essentialSpectrumA": "\\sigma_{\\mathrm{ess}} \\rbk{A}",
  "\\essentialSpectrum": "\\sigma_{\\mathrm{ess}} \\rbk{#1}",
  "\\ev": "\\mathrm{ev}",
  "\\extbbC": "\\ext{\\bbC}",
  "\\extbbRd": "\\ext{\\bbR}^d",
  "\\extbbRnn": "\\ext{\\bbRnonnegative}",
  "\\extbbRnonnegative": "\\ext{\\bbRnonnegative}",
  "\\extbbR": "\\ext{\\bbR}",
  "\\ext": "\\overline{#1}",
  "\\famalphacalIin": "\\setone{#1}_{\\alpha \\in \\calI}",
  "\\famalphacalI": "\\setone{#1_{\\alpha}}_{\\alpha \\in \\calI}",
  "\\familyains": "\\setone{#1}_{\\alpha \\in A}",
  "\\familyain": "\\setone{#1}_{\\alpha \\in A}",
  "\\familyas": "\\setone{#1_{\\alpha}}_{\\alpha \\in A}",
  "\\familya": "\\setone{#1_{\\alpha}}_{\\alpha \\in A}",
  "\\familybins": "\\setone{#1}_{\\beta \\in B}",
  "\\familybin": "\\setone{#1}_{\\beta \\in B}",
  "\\familybs": "\\setone{#1_{\\beta}}_{\\beta \\in B}",
  "\\familyb": "\\setone{#1_{\\beta}}_{\\beta \\in B}",
  "\\familyiiis": "\\setone{#1_i}_{i \\in I}",
  "\\familyiii": "\\setone{#1_i}_{i \\in I}",
  "\\familyiiniis": "\\setone{#1}_{i \\in I}",
  "\\familyiinii": "\\setone{#1}_{i \\in I}",
  "\\familyiins": "\\setone{#1}_{i \\in \\bbN}",
  "\\familyiin": "\\setone{#1}_{i \\in \\bbN}",
  "\\familyis": "\\setone{#1_{i}}_{i \\in \\bbN}",
  "\\familyi": "\\setone{#1_{i}}_{i \\in \\bbN}",
  "\\familyjinjj": "\\setone{#1}_{j \\in J}",
  "\\familyjjinj": "\\setone{#1_j}_{j \\in J}",
  "\\familykins": "\\setone{#1}_{\\kin}",
  "\\familykin": "\\setone{#1}_{\\kin}",
  "\\familyks": "\\setone{#1_{k}}_{\\kin}",
  "\\familyktod": "\\setone{#1_k}_{k=1}^d",
  "\\familykton": "\\setone{#1_k}_{k=1}^n",
  "\\familyk": "\\setone{#1_{k}}_{\\kin}",
  "\\familylins": "\\setone{#1}_{\\lil}",
  "\\familylin": "\\setone{#1}_{\\lil}",
  "\\familyls": "\\setone{#1_{\\lambda}}_{\\lil}",
  "\\familyl": "\\setone{#1_{\\lambda}}_{\\lil}",
  "\\familymins": "\\setone{#1}_{m \\in \\bbN}",
  "\\familymin": "\\setone{#1}_{m \\in \\bbN}",
  "\\familyms": "\\setone{#1_m}_{m \\in \\bbN}",
  "\\familymuinnat": "\\setone{#1}_{\\mu \\in \\bbN}",
  "\\familymuin": "\\setone{#1}_{\\mu \\in \\bbN}",
  "\\familymunat": "\\setone{#1_{\\mu}}_{\\mu \\in \\bbN}",
  "\\familymu": "\\setone{#1_{\\mu}}_{\\mu \\in \\bbN}",
  "\\familym": "\\setone{#1_{\\mu}}_{\\mu \\in M}",
  "\\familynins": "\\setone{#1}_{\\nin}",
  "\\familynin": "\\setone{#1}_{\\nin}",
  "\\familyns": "\\setone{#1_n}_{\\nin}",
  "\\familynuin": "\\setone{#1}_{\\nu \\in \\bbN}",
  "\\familynu": "\\setone{#1_{\\nu}}_{\\nu \\in \\bbN}",
  "\\familyn": "\\setone{#1_n}_{\\nin}",
  "\\familytbbRins": "\\setone{#1}_{t \\in \\bbR}",
  "\\familytbbRin": "\\setone{#1}_{t \\in \\bbR}",
  "\\familytbbRs": "\\setone{#1_t}_{t \\in \\bbR}",
  "\\familytbbR": "\\setone{#1_t}_{t \\in \\bbR}",
  "\\familytnonnegin": "\\setone{#1}_{t \\geq 0}",
  "\\familytnonneg": "\\setone{#1_t}_{t \\geq 0}",
  "\\familyxins": "\\rbk{#1}_{x \\in X}",
  "\\familyxin": "\\setone{#1}_{x \\in X}",
  "\\familyxs": "\\setone{#1_x}_{x \\in X}",
  "\\familyx": "\\setone{#1_x}_{x \\in X}",
  "\\familyzins": "\\setone{#1}_{\\niz}",
  "\\familyzin": "\\setone{#1}_{\\niz}",
  "\\familyzs": "\\setone{#1_n}_{\\niz}",
  "\\familyz": "\\setone{#1_n}_{\\niz}",
  "\\famkbbN": "\\setone{#1_k}_{k \\in \\bbN}",
  "\\famkinbbN": "\\setone{#1}_{k \\in \\bbN}",
  "\\famlamin": "\\setone{#1}_{\\lil}",
  "\\famlam": "\\setone{#1_{\\lambda}}_{\\lil}",
  "\\famnin": "\\setone{#1}_{\\nin}",
  "\\famnonein": "\\setone{#1}_{\\ninone}",
  "\\famnone": "\\setone{#1_n}_{\\ninone}",
  "\\famnzin": "\\setone{#1}_{\\niz}",
  "\\famnz": "\\setone{#1_n}_{\\niz}",
  "\\famn": "\\setone{#1_n}_{\\nin}",
  "\\finite": "#1_{\\mathrm{fin}}",
  "\\fin": "\\hfill $\\square$ \\par",
  "\\floorfunc": "\\lfloor #1 \\rfloor",
  "\\fn": "(f_n)_{n{\\in}{\\bN}}",
  "\\fourpi": "4 \\pi",
  "\\frakA": "\\mathfrak{A}",
  "\\frakB": "\\mathfrak{B}",
  "\\frakC": "\\mathfrak{C}",
  "\\frakD": "\\mathfrak{D}",
  "\\frakE": "\\mathfrak{E}",
  "\\frakF": "\\mathfrak{F}",
  "\\frakG": "\\mathfrak{G}",
  "\\frakH": "\\mathfrak{H}",
  "\\frakI": "\\mathfrak{I}",
  "\\frakJ": "\\mathfrak{J}",
  "\\frakK": "\\mathfrak{K}",
  "\\frakL": "\\mathfrak{L}",
  "\\frakM": "\\mathfrak{M}",
  "\\frakN": "\\mathfrak{N}",
  "\\frakO": "\\mathfrak{O}",
  "\\frakPfin": "\\mathfrak{P}_{\\mathrm{fin}}",
  "\\frakP": "\\mathfrak{P}",
  "\\frakQ": "\\mathfrak{Q}",
  "\\frakR": "\\mathfrak{R}",
  "\\frakS": "\\mathfrak{S}",
  "\\frakT": "\\mathfrak{T}",
  "\\frakU": "\\mathfrak{U}",
  "\\frakV": "\\mathfrak{V}",
  "\\frakW": "\\mathfrak{W}",
  "\\frakXLG": "\\mathfrak{X}^L(G)",
  "\\frakXL": "\\mathfrak{X}^L",
  "\\frakX": "\\mathfrak{X}",
  "\\frakY": "\\mathfrak{Y}",
  "\\frakZ": "\\mathfrak{Z}",
  "\\fraka": "\\mathfrak{a}",
  "\\frakb": "\\mathfrak{b}",
  "\\frakc": "\\mathfrak{c}",
  "\\frakd": "\\mathfrak{d}",
  "\\frake": "\\mathfrak{e}",
  "\\frakf": "\\mathfrak{f}",
  "\\frakgbbC": "\\mathfrak{g}_{\\bbC}",
  "\\frakgl": "\\mathfrak{gl}",
  "\\frakg": "\\mathfrak{g}",
  "\\frakh": "\\mathfrak{h}",
  "\\fraki": "\\mathfrak{i}",
  "\\frakj": "\\mathfrak{j}",
  "\\frakk": "\\mathfrak{k}",
  "\\frakl": "\\mathfrak{l}",
  "\\frakm": "\\mathfrak{m}",
  "\\frakn": "\\mathfrak{n}",
  "\\frako": "\\mathfrak{o}",
  "\\frakp": "\\mathfrak{p}",
  "\\frakq": "\\mathfrak{q}",
  "\\frakr": "\\mathfrak{r}",
  "\\fraksl": "\\mathfrak{sl}",
  "\\frakso": "\\mathfrak{so}",
  "\\fraksp": "\\mathfrak{sp}",
  "\\fraksu": "\\mathfrak{su}",
  "\\fraks": "\\mathfrak{s}",
  "\\frakt": "\\mathfrak{t}",
  "\\fraku": "\\mathfrak{u}",
  "\\frakv": "\\mathfrak{v}",
  "\\frakw": "\\mathfrak{w}",
  "\\frakx": "\\mathfrak{x}",
  "\\fraky": "\\mathfrak{y}",
  "\\frakz": "\\mathfrak{z}",
  "\\free": "\\mathrm{fr}",
  "\\fun": "#1 \\rbk{#2}",
  "\\fxn": "(f (x_n))_{n{\\in}{\\bN}}",
  "\\gepminus": "g_{\\ep}^{-}",
  "\\gepplus": "g_{\\ep}^{+}",
  "\\germ": "\\underline{#1}_{#2}",
  "\\gone": "\\setSymbolDownLeft{1}{g}",
  "\\gonerbkt": "\\gone \\rbkt{#1}{#2}",
  "\\gtwo": "\\setSymbolDownLeft{2}{g}",
  "\\gtworbkt": "\\gtwo \\rbkt{#1}{#2}",
  "\\highlightcap": "\\tikz[baseline=(x.base)]{\\node[rectangle,rounded corners,fill=#1!10](x){#2} node[below of=x, color=#1]{#3};}",
  "\\highlight": "\\tikz[baseline=(x.base)]{\\node[rectangle,rounded corners,fill=#1!10](x){#2};}",
  "\\homo": "\\mathrm{Hom}",
  "\\hyperbolicsegment": "\\left[ #1, \\, #2 \\right]_{\\mathrm{h}}",
  "\\id": "\\mathrm{id}",
  "\\iii": "i \\in I",
  "\\imunit": "\\sqrt{-1}",
  "\\inftynorms": "\\Vert #1 \\Vert_{\\infty}",
  "\\inftynorm": "\\norm{ #1 }_{\\infty}",
  "\\injsh": "\\mathcal{I}",
  "\\intOmega": "\\int_{\\Omega}",
  "\\intX": "\\int_{X}",
  "\\intbbRN": "\\int_{\\bbRN}",
  "\\intbbRdN": "\\int_{\\bbRdN}",
  "\\intbbRdk": "\\int_{\\bbRdk}",
  "\\intbbRdn": "\\int_{\\bbRdn}",
  "\\intbbRdx": "\\int_{\\bbRdx}",
  "\\intbbRd": "\\int_{\\bbRd}",
  "\\intbbRthreeN": "\\int_{\\bbRthreeN}",
  "\\intbbRthreek": "\\int_{\\bbRthreek}",
  "\\intbbRthreex": "\\int_{\\bbRthreex}",
  "\\intbbRthree": "\\int_{\\bbRthree}",
  "\\intbbR": "\\int_{\\bbR}",
  "\\intzeroinfty": "\\int_0^{\\infty}",
  "\\inverseA": "A^{-1}",
  "\\inverseU": "U^{-1}",
  "\\inversef": "f^{-1}",
  "\\inverseg": "g^{-1}",
  "\\inverse": "#1^{-1}",
  "\\inv": "#1^{-1}",
  "\\iphi": "i \\phi",
  "\\ipsi": "i \\psi",
  "\\itheta": "i \\theta",
  "\\jpcomb": "{}_{#1} \\mathrm{C}_{#2}",
  "\\ketbra": "\\ket{#1} \\bra{#2}",
  "\\ket": "\\left| #1 \\right\\rangle",
  "\\kinone": "k \\in \\bbNone",
  "\\kin": "k \\in \\bbN",
  "\\kti": "k \\to \\infty",
  "\\lambdak": "\\lambda^{\\kappa}",
  "\\leftopeninterval": "\\left(#1, \\, #2 \\right]",
  "\\lieg": "\\mathfrak{g}",
  "\\liegl": "\\mathfrak{gl}",
  "\\lieh": "\\mathfrak{h}",
  "\\lieo": "\\mathfrak{o}",
  "\\liesl": "\\mathfrak{sl}",
  "\\lieso": "\\mathfrak{so}",
  "\\liesp": "\\mathfrak{sp}",
  "\\liesu": "\\mathfrak{su}",
  "\\lieu": "\\mathfrak{u}",
  "\\lil": "\\lambda \\in \\Lambda",
  "\\limMtoinfty": "\\lim_{M \\to \\infty}",
  "\\limNtoinfty": "\\lim_{N \\to \\infty}",
  "\\limabssztoinfty": "\\lim_{\\abs{z} \\to \\infty}",
  "\\limhtozero": "\\lim_{h \\to 0}",
  "\\liminfntoinfty": "\\liminf_{n \\to \\infty}",
  "\\limjtoinfty": "\\lim_{j \\to \\infty}",
  "\\limktoinfty": "\\lim_{k \\to \\infty}",
  "\\limltoinfty": "\\lim_{l \\to \\infty}",
  "\\limmtoinfty": "\\lim_{m \\to \\infty}",
  "\\limntoinfty": "\\lim_{n \\to \\infty}",
  "\\limsupntoinfty": "\\limsup_{n \\to \\infty}",
  "\\limttozero": "\\lim_{t \\to 0}",
  "\\limxtoinfty": "\\lim_{x \\to \\infty}",
  "\\limxtominusinfty": "\\lim_{x \\to - \\infty}",
  "\\logten": "\\log_{10}",
  "\\logtwo": "\\log_2",
  "\\lrto": "\\Longleftrightarrow",
  "\\lti": "l \\to \\infty",
  "\\lto": "\\Longleftarrow",
  "\\mL": "m_{\\rm{L}}",
  "\\mbC": "\\mathbb{C}",
  "\\mbN": "\\mathbb{N}",
  "\\mbQ": "\\mathbb{Q}",
  "\\mbR": "\\mathbb{R}",
  "\\mbZ": "\\mathbb{Z}",
  "\\mb": "\\mbox{\\boldmath $#1$}",
  "\\mcb": "\\mathcal{B}",
  "\\mcl": "\\mathcal{L}",
  "\\mcm": "\\mathcal{M}",
  "\\mco": "\\mathcal{O}",
  "\\mcp": "\\mathcal{P}",
  "\\mcr": "\\mathcal{R}",
  "\\mcs": "\\mathcal{S}",
  "\\meanphys": "\\left\\langle #1 \\right\\rangle",
  "\\measae": "#1 \\myhyphen \\mathrm{a.e.} #2",
  "\\measas": "#1 \\myhyphen \\mathrm{a.s.} #2",
  "\\middleslash": "\\left. #1 \\middle/ #2 \\right.",
  "\\minusket": "\\ket{-}",
  "\\modr": "\\Mod \\mathchar`- R",
  "\\mrm": "\\mathrm{#1}",
  "\\mti": "m \\to \\infty",
  "\\muD": "\\mu^{\\rm{D}}",
  "\\muLd": "\\mu_{\\rm{L}}^d",
  "\\muLk": "\\mu_{k, \\rm{L}}",
  "\\muLoeb": "\\mu_{\\rm{Loeb}}",
  "\\muLouter": "\\mu_{\\rm{L}}^{*}",
  "\\muLx": "\\mu_{x, \\rm{L}}",
  "\\muL": "\\mu_{\\rm{L}}",
  "\\mucount": "\\mu_{\\rm{c}}",
  "\\muouter": "\\mu^{*}",
  "\\muzero": "\\mu_0",
  "\\myae": "(\\mathrm{a.e.})",
  "\\myast": "*",
  "\\myas": "(\\mathrm{a.s.})",
  "\\mycelcius": "{}^{\\circ}\\mathrm{C}",
  "\\mycomplement": "#1^{c}",
  "\\mydisjointunionl": "\\coprod_{\\lil} #1_{\\lambda}",
  "\\mydisjointunionnin": "\\coprod_{\\nin} #1",
  "\\mydisjointunionn": "\\coprod_{\\nin} #1_n",
  "\\mydisjointunionton": "\\coprod_{k=0}^n #1_k",
  "\\myexp": "\\exp \\rbk{#1}",
  "\\mygauss": "\\left\\lfloor #1 \\right\\rfloor",
  "\\myhyphen": "\\hbox{-}",
  "\\myie": "\\mathrm{i.e.}",
  "\\myintersectionl": "\\bigcap_{\\lil} #1_{\\lambda}",
  "\\myintersectionn": "\\bigcap_{\\nin} #1_n",
  "\\myintersectionton": "\\bigcap_{k=0}^n #1_k",
  "\\mynvec": "\\underline{\\boldsymbol{#1}}_{#2}",
  "\\myperp": "#1^{\\perp}",
  "\\myprodn": "\\prod_{n=0}^{\\infty}",
  "\\myprodton": "\\prod_{k=0}^n",
  "\\myquotefile": "{\\footnotesize\\verbatimtabinput[2]{#1}}",
  "\\myrestriction": "\\left. #1 \\right|_{#2}",
  "\\mysimpleae": "\\mathrm{a.e.}",
  "\\mysumn": "\\sum_{n=0}^{\\infty}",
  "\\mysumtod": "\\sum_{k=0}^d",
  "\\mysumton": "\\sum_{k=0}^n",
  "\\myunioniin": "\\bigcup_{i \\in I} #1",
  "\\myunioni": "\\bigcup_{i \\in I} #1_{i}",
  "\\myunionl": "\\bigcup_{\\lil} #1_{\\lambda}",
  "\\myunionm": "\\bigcup_{m \\in \\bbN} #1_m",
  "\\myunionnin": "\\bigcup_{\\nin} #1",
  "\\myunionn": "\\bigcup_{\\nin} #1_n",
  "\\myuniontonin": "\\bigcup_{k=0}^n #1",
  "\\myunionton": "\\bigcup_{k=0}^n #1_k",
  "\\myvertical": "\\left. #1 \\right|",
  "\\nablaE": "\\nabla^E",
  "\\ninbbNone": "n \\in \\bbNone",
  "\\ninone": "n \\in \\bbNone",
  "\\nin": "n \\in \\bbN",
  "\\niz": "n \\in \\bbZ",
  "\\norms": "\\Vert #1 \\Vert",
  "\\norm": "\\left\\Vert #1 \\right\\Vert",
  "\\nsbbC": "\\setSymbolUpLeft{*}{\\bbC}",
  "\\nsbbN": "\\setSymbolUpLeft{*}{\\bbN}",
  "\\nsbbQ": "\\setSymbolUpLeft{*}{\\bbQ}",
  "\\nsbbR": "\\setSymbolUpLeft{*}{\\bbR}",
  "\\ns": "\\setSymbolUpLeft{*}{#1}",
  "\\nti": "n \\to \\infty",
  "\\nuouter": "\\nu^{*}",
  "\\odop": "\\frac{d}{d #1}",
  "\\od": "\\frac{d #1}{d #2}",
  "\\oneParGbbRin": "\\cbk{#1}_{t \\in \\bbR}",
  "\\oneParGbbR": "\\cbk{#1_t}_{t \\in \\bbR}",
  "\\onenorms": "\\Vert #1 \\Vert_1",
  "\\onenorm": "\\norm{ #1 }_1",
  "\\onepnorms": "\\Vert #1 \\Vert_{W^{1,p}}",
  "\\onepnorm": "\\norm{ #1 }_{W^{1,p}}",
  "\\onetwonorms": "\\Vert #1 \\Vert_{W^{1,2}}",
  "\\onetwonorm": "\\norm{ #1 }_{W^{1,2}}",
  "\\opair": "\\dbk{#1}",
  "\\opdc": "\\, dc",
  "\\opdk": "\\, dk",
  "\\opdlambda": "\\, d \\lambda",
  "\\opdmuLx": "\\, d \\muL (x)",
  "\\opdmuLy": "\\, d \\muL (y)",
  "\\opdmuL": "\\, d \\muL",
  "\\opdmux": "\\, d \\mu (x)",
  "\\opdmuy": "\\, d \\mu (y)",
  "\\opdmu": "\\, d \\mu",
  "\\opdnux": "\\, d \\nu (x)",
  "\\opdnuy": "\\, d \\nu (y)",
  "\\opdnu": "\\, d \\nu",
  "\\opdomega": "\\, d \\omega",
  "\\opdp": "\\, dp",
  "\\opdr": "\\, dr",
  "\\opds": "\\, ds",
  "\\opdtheta": "\\, d \\theta",
  "\\opdt": "\\, dt",
  "\\opdu": "\\, du",
  "\\opdv": "\\, dv",
  "\\opdw": "\\, dw",
  "\\opdx": "\\, dx",
  "\\opdy": "\\, dy",
  "\\opdz": "\\, dz",
  "\\opd": "\\, d",
  "\\opnorms": "\\Vert #1 \\Vert_{\\mathrm{op}}",
  "\\opnorm": "\\left\\Vert #1 \\right\\Vert_{\\mathrm{op}}",
  "\\opposite": "\\mathrm{op}",
  "\\outerppullbacks": "\\rbks{#1^{*}}",
  "\\outerppullback": "\\rbk{#1^{*}}",
  "\\outerppushouts": "\\rbks{#1_{*}}",
  "\\outerppushout": "\\rbk{#1_{*}}",
  "\\overarc": "\\stackrel{\\Large\\mbox{$\\frown$}}{#1}",
  "\\paadjoints": "\\rbks{#1}^{**}",
  "\\paadjoint": "\\rbk{#1}^{**}",
  "\\pabss": "| #1 |_p",
  "\\pabs": "\\left|#1\\right|_p",
  "\\padjoints": "\\rbks{#1}^{*}",
  "\\padjoint": "\\adjoint{\\rbk{#1}}",
  "\\pclosures": "\\overline{\\rbks{#1}}",
  "\\pclosure": "\\overline{\\rbk{#1}}",
  "\\pcoloredtextbf": "\\textbf{\\textcolor{blue}{(#1)}}",
  "\\pconjugates": "\\overline{\\rbks{#1}}",
  "\\pconjugate": "\\overline{\\rbk{#1}}",
  "\\pdduals": "\\rbks{#1}^{**}",
  "\\pddual": "\\rbk{#1}^{**}",
  "\\pdftovf": "\\rbk{#1}^{\\sharp}",
  "\\pdist": "\\left|#1\\right|_{p}",
  "\\pdk": "\\frac{\\partial #1}{\\partial k_{#2}}",
  "\\pdop": "\\frac{\\partial}{\\partial #1}",
  "\\pdpds": "\\frac{\\partial}{\\partial t}",
  "\\pdpdt": "\\frac{\\partial}{\\partial t}",
  "\\pdpdx": "\\frac{\\partial}{\\partial t}",
  "\\pdpdy": "\\frac{\\partial}{\\partial t}",
  "\\pduals": "\\rbks{#1}^{*}",
  "\\pdual": "\\rbk{#1}^{*}",
  "\\pdxop": "\\frac{\\partial}{\\partial x_{#1}}",
  "\\pdx": "\\frac{\\partial #1}{\\partial x_{#2}}",
  "\\pdyop": "\\frac{\\partial}{\\partial y_{#1}}",
  "\\pdy": "\\frac{\\partial #1}{\\partial y_{#2}}",
  "\\pd": "\\frac{\\partial #1}{\\partial #2}",
  "\\perm": "{}_{#1} \\mathrm{P}_{#2}",
  "\\pfun": "\\rbk{#1} \\rbk{#2}",
  "\\phirhol": "\\phi_{\\rho, \\mathrm{l}}",
  "\\physconjugate": "{#1}^{*}",
  "\\physmean": "\\left\\langle #1 \\right\\rangle",
  "\\pihalf": "\\frac{\\pi}{2}",
  "\\pibetaAW": "\\pi_{\\beta}^{\\mathrm{AW}}",
  "\\pinverse": "\\rbk{#1}^{-1}",
  "\\pinv": "\\rbk{#1}^{-1}",
  "\\plusket": "\\ket{+}",
  "\\pmycomplement": "\\rbk{#1}^{c}",
  "\\pmyperps": "\\rbks{#1}^{\\perp}",
  "\\pmyperp": "\\rbk{#1}^{\\perp}",
  "\\pmyrestriction": "\\left. \\rbk{#1} \\right|_{#2}",
  "\\pnorms": "\\Vert #1 \\Vert_p",
  "\\pnorm": "\\left\\Vert #1 \\right\\Vert_p",
  "\\pns": "\\setSymbolUpLeft{*}{\\rbk{#1}}",
  "\\pn": "(p_n)_{n{\\in}{\\bN}}",
  "\\pointSpectrumA": "\\sigma_{\\mathrm{p}} \\rbk{A}",
  "\\pointSpectrum": "\\sigma_{\\mathrm{p}} \\rbk{#1}",
  "\\ppd": "\\frac{\\partial^2 #1}{\\partial #2^2}",
  "\\pppushouts": "\\rbks{\\rbks{#1}_{*}}",
  "\\pppushout": "\\rbk{\\rbk{#1}_{*}}",
  "\\ppullbacks": "\\rbks{#1}^{*}",
  "\\ppullback": "\\rbk{#1}^{*}",
  "\\ppushouts": "\\rbks{#1}_{*}",
  "\\ppushout": "\\rbk{#1}_{*}",
  "\\pqcotsp": "T_{#1}^{*,(#3)} #2",
  "\\pqtansp": "T_{#1}^{(#3)} #2",
  "\\predualcalM": "\\predual{\\calM}",
  "\\predual": "#1_{*}",
  "\\preverse": "\\rbk{#1}^{-}",
  "\\pr": "\\mathrm{pr}",
  "\\pstar": "p^{\\star}",
  "\\pstmap": "\\setSymbolUpLeft{\\circ}{\\rbk{#1}}",
  "\\ptextbf": "\\textbf{(#1)}",
  "\\ptranspose": "\\setSymbolUpLeft{t}{\\rbk{#1}}",
  "\\pt": "\\mathrm{pt}",
  "\\pullbackf": "\\pullback{f}",
  "\\pullback": "#1^{*}",
  "\\punitclosedballXs": "\\rbks{X}_1",
  "\\punitclosedballX": "\\rbk{X}_1",
  "\\punitclosedballdualXs": "\\rbks{\\dualX}_1",
  "\\punitclosedballdualX": "\\rbk{\\dualX}_1",
  "\\punitclosedballscalH": "\\rbks{\\calH}_1",
  "\\punitclosedballs": "\\rbks{#1}_1",
  "\\punitclosedball": "\\rbk{#1}_1",
  "\\pureq": "\\bbR \\boldi + \\bbR \\boldj + \\bbR \\boldk",
  "\\pushout": "#1_{*}",
  "\\pvftodf": "\\rbk{#1}^{\\flat}",
  "\\qabss": "| #1 |_q",
  "\\qabs": "\\left|#1\\right|_q",
  "\\qnorms": "\\Vert #1 \\Vert_q",
  "\\qnorm": "\\left\\Vert #1 \\right\\Vert_q",
  "\\rbkconds": "\\rbks{#1 \\, \\middle| \\, #2}",
  "\\rbkcond": "\\rbk{#1 \\, \\middle| \\, #2}",
  "\\rbkfrac": "\\rbk{\\frac{#1}{#2}}",
  "\\rbks": "( #1 )",
  "\\rbkts": "( #1,\\,#2)",
  "\\rbktvert": "\\left( #1, \\vert #2 \\right)",
  "\\rbktwopid": "\\rbk{\\twopi}^{d}",
  "\\rbkt": "\\left( #1,\\,#2 \\right)",
  "\\rbk": "\\left( #1 \\right)",
  "\\realrapiddecrease": "\\mathcal{S}_{\\mathrm{real}}",
  "\\realtempereddist": "\\mathcal{S}'_{\\mathrm{real}}",
  "\\relmiddle": "\\mathrel{}\\middle#1\\mathrel{}",
  "\\residualSpectrumA": "\\sigma_{\\mathrm{r}} \\rbk{A}",
  "\\residualSpectrum": "\\sigma_{\\mathrm{r}} \\rbk{#1}",
  "\\resolventA": "\\rho (A)",
  "\\resolvent": "\\rho (#1)",
  "\\reverse": "#1^{-}",
  "\\rhoNinfty": "\\rho_{N, \\infty}",
  "\\rhoalphabeta": "\\rho_{\\beta}^{\\alpha}",
  "\\rhobeta": "\\rho_{\\beta}",
  "\\riemannsphere": "\\overline{\\bbC}",
  "\\rightopeninterval": "\\left[#1, \\, #2 \\right)",
  "\\rmAIC": "\\mathrm{AIC}",
  "\\rmA": "\\mathrm{A}",
  "\\rmB": "\\mathrm{B}",
  "\\rmCh": "\\mathrm{Ch}",
  "\\rmC": "\\mathrm{C}",
  "\\rmEAP": "\\mathrm{EAP}",
  "\\rmE": "\\mathrm{E}",
  "\\rmF": "\\mathrm{F}",
  "\\rmGL": "\\mathrm{GL}",
  "\\rmG": "\\mathrm{G}",
  "\\rmIm": "\\mathrm{Im}",
  "\\rmI": "\\mathrm{I}",
  "\\rmJ": "\\mathrm{J}",
  "\\rmL": "\\mathrm{L}",
  "\\rmM": "\\mathrm{M}",
  "\\rmN": "\\mathrm{N}",
  "\\rmO": "\\mathrm{O}",
  "\\rmProb": "\\mathrm{Prob}",
  "\\rmPr": "\\mathrm{Pr} \\rbk{#1}",
  "\\rmRe": "\\mathrm{Re}",
  "\\rmSL": "\\mathrm{SL}",
  "\\rmSO": "\\mathrm{SO}",
  "\\rmSU": "\\mathrm{SU}",
  "\\rmSpin": "\\mathrm{Spin}",
  "\\rmSp": "\\mathrm{Sp}",
  "\\rmS": "\\mathrm{S}",
  "\\rmT": "\\mathrm{T}",
  "\\rmU": "\\mathrm{U}",
  "\\rmV": "\\mathrm{V}",
  "\\rmWAIC": "\\mathrm{WAIC}",
  "\\rmW": "\\mathrm{W}",
  "\\rmX": "\\mathrm{X}",
  "\\rmY": "\\mathrm{Y}",
  "\\rmZ": "\\mathrm{Z}",
  "\\rmac": "\\mathrm{ac}",
  "\\rmap": "\\mathrm{ap}",
  "\\rmas": "\\mathrm{as}",
  "\\rmb": "\\mathrm{b}",
  "\\rmcir": "\\mathrm{cir}",
  "\\rmcl": "\\mathrm{cl}",
  "\\rmc": "\\mathrm{c}",
  "\\rmd": "\\mathrm{d}",
  "\\rmeV": "\\mathrm{eV}",
  "\\rmerf": "\\mathrm{erf}",
  "\\rmev": "\\mathrm{ev}",
  "\\rme": "\\mathrm{e}",
  "\\rmfin": "\\mathrm{fin}",
  "\\rmfr": "\\mathrm{fr}",
  "\\rmf": "\\mathrm{f}",
  "\\rmg": "\\mathrm{g}",
  "\\rmh": "\\mathrm{h}",
  "\\rmio": "\\mathrm{io}",
  "\\rmirr": "\\mathrm{irr}",
  "\\rmirs": "\\mathrm{irs}",
  "\\rmi": "\\mathrm{i}",
  "\\rmkg": "\\mathrm{kg}",
  "\\rmloc": "\\mathrm{loc}",
  "\\rmmax": "\\mathrm{max}",
  "\\rmmin": "\\mathrm{min}",
  "\\rmm": "\\mathrm{m}",
  "\\rmod": "R \\mathchar`- \\Mod",
  "\\rmph": "\\mathrm{ph}",
  "\\rmps": "\\mathrm{ps}",
  "\\rmp": "\\mathrm{p}",
  "\\rmrad": "\\mathrm{rad}",
  "\\rmr": "\\mathrm{r}",
  "\\rmst": "\\mathrm{st}",
  "\\rms": "\\mathrm{s}",
  "\\rmtot": "\\mathrm{tot}",
  "\\rmw": "\\mathrm{w}",
  "\\rnorms": "\\Vert #1 \\Vert_r",
  "\\rnorm": "\\left\\Vert #1 \\right\\Vert_r",
  "\\rotationvectorproduct": "\\vectorproduct{\\nabla}{#1}",
  "\\rto": "\\Longrightarrow",
  "\\sbigtensor": "\\bigotimes_{\\mathrm{s}}",
  "\\scrA": "\\mathscr{A}",
  "\\scrB": "\\mathscr{B}",
  "\\scrCinfty": "\\mathscr{C}^{\\infty}",
  "\\scrC": "\\mathscr{C}",
  "\\scrD": "\\mathscr{D}",
  "\\scrE": "\\mathscr{E}",
  "\\scrF": "\\mathscr{F}",
  "\\scrG": "\\mathscr{G}",
  "\\scrH": "\\mathscr{H}",
  "\\scrI": "\\mathscr{I}",
  "\\scrJ": "\\mathscr{J}",
  "\\scrK": "\\mathscr{K}",
  "\\scrL": "\\mathscr{L}",
  "\\scrMtimes": "\\mathscr{M}^{\\times}",
  "\\scrM": "\\mathscr{M}",
  "\\scrN": "\\mathscr{N}",
  "\\scrOtimes": "\\mathscr{O}^{\\times}",
  "\\scrO": "\\mathscr{O}",
  "\\scrP": "\\mathscr{P}",
  "\\scrQ": "\\mathscr{Q}",
  "\\scrR": "\\mathscr{R}",
  "\\scrS": "\\mathscr{S}",
  "\\scrT": "\\mathscr{T}",
  "\\scrU": "\\mathscr{U}",
  "\\scrV": "\\mathscr{V}",
  "\\scrW": "\\mathscr{W}",
  "\\scrX": "\\mathscr{X}",
  "\\scrY": "\\mathscr{Y}",
  "\\scrZ": "\\mathscr{Z}",
  "\\scra": "\\mathscr{a}",
  "\\scrb": "\\mathscr{b}",
  "\\scrc": "\\mathscr{c}",
  "\\scrd": "\\mathscr{d}",
  "\\scre": "\\mathscr{e}",
  "\\scrf": "\\mathscr{f}",
  "\\scrg": "\\mathscr{g}",
  "\\scrh": "\\mathscr{h}",
  "\\scri": "\\mathscr{i}",
  "\\scrj": "\\mathscr{j}",
  "\\scrk": "\\mathscr{k}",
  "\\scrl": "\\mathscr{l}",
  "\\scrm": "\\mathscr{m}",
  "\\scrn": "\\mathscr{n}",
  "\\scro": "\\mathscr{o}",
  "\\scrp": "\\mathscr{p}",
  "\\scrq": "\\mathscr{q}",
  "\\scrr": "\\mathscr{r}",
  "\\scrs": "\\mathscr{s}",
  "\\scrt": "\\mathscr{t}",
  "\\scru": "\\mathscr{u}",
  "\\scrv": "\\mathscr{v}",
  "\\scrw": "\\mathscr{w}",
  "\\scrx": "\\mathscr{x}",
  "\\scry": "\\mathscr{y}",
  "\\scrz": "\\mathscr{z}",
  "\\seqMin": "\\rbk{#1}_{M \\in \\bbN}",
  "\\seqM": "\\rbk{#1_N}_{M \\in \\bbN}",
  "\\seqNin": "\\rbk{#1}_{N \\in \\bbN}",
  "\\seqNonein": "\\rbk{#1}_{\\ninone}",
  "\\seqNone": "\\rbk{#1_N}_{\\ninone}",
  "\\seqN": "\\rbk{#1_N}_{N \\in \\bbN}",
  "\\seqalphacalIin": "\\rbk{#1}_{\\alpha \\in \\calI}",
  "\\seqalphacalI": "\\rbk{#1_{\\alpha}}_{\\alpha \\in \\calI}",
  "\\seqalphafrakIin": "\\rbk{#1}_{\\alpha \\in \\frakI}",
  "\\seqalphafrakI": "\\rbk{#1_{\\alpha}}_{\\alpha \\in \\frakI}",
  "\\seqbetannin": "\\rbk{#1}_{\\beta \\geq 0}",
  "\\seqbetann": "\\rbk{#1_\\beta}_{\\beta \\geq 0}",
  "\\seqeppluss": "(#1_\\ep)_{\\ep > 0}",
  "\\seqepplus": "\\rbk{#1_\\ep}_{\\ep > 0}",
  "\\seqiIin": "\\rbk{#1}_{i \\in I}",
  "\\seqiI": "\\rbk{#1_{i}}_{i \\in I}",
  "\\seqiin": "\\rbk{#1}_{i \\in \\bbN}",
  "\\seqi": "\\rbk{#1_{j}}_{i \\in \\bbN}",
  "\\seqjijin": "\\rbk{#1_{j}}_{j \\in J}",
  "\\seqjij": "\\rbk{#1_{j}}_{j \\in J}",
  "\\seqjin": "\\rbk{#1}_{j \\in \\bbN}",
  "\\seqj": "\\rbk{#1_{j}}_{j \\in \\bbN}",
  "\\seqkin": "\\rbk{#1}_{k \\in \\bbN}",
  "\\seqkonein": "\\rbk{#1}_{k \\in \\bbNone}",
  "\\seqkone": "\\rbk{#1_{k}}_{k \\in \\bbNone}",
  "\\seqk": "\\rbk{#1_{k}}_{k \\in \\bbN}",
  "\\seqlamin": "\\rbk{#1}_{\\lil}",
  "\\seqlam": "\\rbk{#1_{\\lambda}}_{\\lil}",
  "\\seqlin": "\\rbk{#1}_{l \\in \\bbN}",
  "\\seql": "\\rbk{#1_{l}}_{l \\in \\bbN}",
  "\\seqmin": "\\rbk{#1}_{m \\in \\bbN}",
  "\\seqmuin": "\\rbk{#1}_{\\mu \\in M}",
  "\\seqmu": "\\rbk{#1_{\\mu}}_{\\mu \\in M}",
  "\\seqm": "\\rbk{#1_{m}}_{m\\in \\bbN}",
  "\\seqmonein": "\\rbk{#1}_{m \\in \\bbNone}",
  "\\seqmone": "\\rbk{#1_{m}}_{m\\in \\bbNone}",
  "\\seqnatins": "(#1)_{\\nin}",
  "\\seqnatin": "\\rbk{#1}_{\\nin}",
  "\\seqnatis": "(#1_i)_{i \\in \\bbN}",
  "\\seqnati": "\\rbk{#1_i}_{i \\in \\bbN}",
  "\\seqnatkins": "\\rbks{#1}_{k \\in \\bbN}",
  "\\seqnatkin": "\\rbk{#1}_{k \\in \\bbN}",
  "\\seqnatks": "\\rbks{#1_k}_{k \\in \\bbN}",
  "\\seqnatk": "\\rbk{#1_k}_{k \\in \\bbN}",
  "\\seqnatlins": "\\rbks{#1}_{l \\in \\bbN}",
  "\\seqnatlin": "\\rbk{#1}_{l \\in \\bbN}",
  "\\seqnatls": "\\rbks{#1_l}_{l \\in \\bbN}",
  "\\seqnatl": "\\rbk{#1_l}_{l \\in \\bbN}",
  "\\seqnatmins": "(#1)_{m \\in \\bbN}",
  "\\seqnatmin": "\\rbk{#1}_{m \\in \\bbN}",
  "\\seqnatms": "(#1_m)_{m \\in \\bbN}",
  "\\seqnatmuin": "\\rbk{#1}_{\\mu \\in \\bbN}",
  "\\seqnatmu": "\\rbk{#1_{\\mu}}_{\\mu \\in \\bbN}",
  "\\seqnatm": "\\rbk{#1_m}_{m \\in \\bbN}",
  "\\seqnatnuin": "\\rbk{#1}_{\\nu \\in \\bbN}",
  "\\seqnatnu": "\\rbk{#1_{\\nu}}_{\\nu \\in \\bbN}",
  "\\seqnats": "(#1_n)_{\\nin}",
  "\\seqnat": "\\rbk{#1_n}_{\\nin}",
  "\\seqnin": "\\rbk{#1}_{\\nin}",
  "\\seqnonein": "\\rbk{#1}_{\\ninone}",
  "\\seqnone": "\\rbk{#1_n}_{\\ninone}",
  "\\seqns": "\\rbk{#1_n}_{n \\in \\nsbbN}",
  "\\seqn": "\\rbk{#1_n}_{\\nin}",
  "\\seqrpluss": "(#1_r)_{r>0}",
  "\\seqrplus": "\\rbk{#1_r}_{r>0}",
  "\\seqsnnin": "\\rbk{#1}_{s \\geq 0}",
  "\\seqsnn": "\\rbk{#1_s}_{s \\geq 0}",
  "\\seqsnonnegativein": "\\rbk{#1}_{s \\geq 0}",
  "\\seqsnonnegative": "\\rbk{#1_s}_{s \\geq 0}",
  "\\seqszerotoone": "\\rbk{#1_s}_{s \\in [0,1]}",
  "\\seqtIin": "\\rbk{#1}_{t \\in I}",
  "\\seqtI": "\\rbk{#1_t}_{t \\in I}",
  "\\seqtabin": "\\rbk{#1}_{t \\in [a,b]}",
  "\\seqtab": "\\rbk{#1_t}_{t \\in [a,b]}",
  "\\seqtnnin": "\\rbk{#1}_{t \\geq 0}",
  "\\seqtnn": "\\rbk{#1_t}_{t \\geq 0}",
  "\\seqtreals": "\\rbks{#1_t}_{t \\in \\bbR}",
  "\\seqtreal": "\\rbk{#1_t}_{t \\in \\bbR}",
  "\\seq": "\\rbk{#1}",
  "\\setSymbolDownLeft": "{\\vphantom{#2}}_{#1}{#2}",
  "\\setSymbolUpLeft": "{\\vphantom{#2}}^{#1}{#2}",
  "\\setminussetonezero": "\\setminus \\setonezero",
  "\\setonezero": "\\setone{0}",
  "\\setone": "\\cbk{#1}",
  "\\set": "\\left\\{#1 \\, \\middle| \\, #2\\right\\}",
  "\\sfA": "\\mathsf{A}",
  "\\sfB": "\\mathsf{B}",
  "\\sfC": "\\mathsf{C}",
  "\\sfD": "\\mathsf{D}",
  "\\sfE": "\\mathsf{E}",
  "\\sfF": "\\mathsf{F}",
  "\\sfG": "\\mathsf{G}",
  "\\sfH": "\\mathsf{H}",
  "\\sfI": "\\mathsf{I}",
  "\\sfJ": "\\mathsf{J}",
  "\\sfK": "\\mathsf{K}",
  "\\sfL": "\\mathsf{L}",
  "\\sfM": "\\mathsf{M}",
  "\\sfN": "\\mathsf{N}",
  "\\sfO": "\\mathsf{O}",
  "\\sfP": "\\mathsf{P}",
  "\\sfQ": "\\mathsf{Q}",
  "\\sfR": "\\mathsf{R}",
  "\\sfSet": "\\mathsf{Set}",
  "\\sfS": "\\mathsf{S}",
  "\\sfTop": "\\mathsf{Top}",
  "\\sfT": "\\mathsf{T}",
  "\\sfU": "\\mathsf{U}",
  "\\sfV": "\\mathsf{V}",
  "\\sfW": "\\mathsf{W}",
  "\\sfX": "\\mathsf{X}",
  "\\sfY": "\\mathsf{Y}",
  "\\sfZ": "\\mathsf{Z}",
  "\\sfa": "\\mathsf{a}",
  "\\sfb": "\\mathsf{b}",
  "\\sfc": "\\mathsf{c}",
  "\\sfd": "\\mathsf{d}",
  "\\sfe": "\\mathsf{e}",
  "\\sff": "\\mathsf{f}",
  "\\sfg": "\\mathsf{g}",
  "\\sfh": "\\mathsf{h}",
  "\\sfi": "\\mathsf{i}",
  "\\sfj": "\\mathsf{j}",
  "\\sfk": "\\mathsf{k}",
  "\\sfl": "\\mathsf{l}",
  "\\sfm": "\\mathsf{m}",
  "\\sfn": "\\mathsf{n}",
  "\\sfo": "\\mathsf{o}",
  "\\sfp": "\\mathsf{p}",
  "\\sfq": "\\mathsf{q}",
  "\\sfr": "\\mathsf{r}",
  "\\sfs": "\\mathsf{s}",
  "\\sft": "\\mathsf{t}",
  "\\sfu": "\\mathsf{u}",
  "\\sfv": "\\mathsf{v}",
  "\\sfw": "\\mathsf{w}",
  "\\sfx": "\\mathsf{x}",
  "\\sfy": "\\mathsf{y}",
  "\\sfz": "\\mathsf{z}",
  "\\simto": "\\xrightarrow{\\sim}",
  "\\singularSpectrumH": "\\sigma_{\\rms} \\rbk{H}",
  "\\singularSpectrum": "\\sigma_{\\rms} \\rbk{#1}",
  "\\slimMtoinfty": "\\mathrm{s} \\myhyphen \\lim_{M \\to \\infty}",
  "\\slimNtoinfty": "\\mathrm{s} \\myhyphen \\lim_{N \\to \\infty}",
  "\\slimltoinfty": "\\mathrm{s} \\myhyphen \\lim_{\\lti}",
  "\\slimntoinfty": "\\mathrm{s} \\myhyphen \\lim_{\\nti}",
  "\\slrto": "\\Longleftrightarrow",
  "\\slto": "\\Leftarrow",
  "\\specconn": "\\sigma_{\\mathrm{c}} \\rbk{#1}",
  "\\specpoint": "\\sigma_{\\mathrm{p}} \\rbk{#1}",
  "\\specres": "\\sigma_{\\mathrm{r}} \\rbk{#1}",
  "\\spectralFamily": "\\setone{#1_{\\lambda}}_{\\lambda \\in \\bbR}",
  "\\spectrumA": "\\spectrum{A}",
  "\\spectrum": "\\sigma \\rbk{#1}",
  "\\sqbkconds": "\\sqbks{#1 \\, \\middle| \\, #2}",
  "\\sqbkcond": "\\sqbk{#1 \\, \\middle| \\, #2}",
  "\\sqbks": "[ #1 ]",
  "\\sqbkt": "\\left[ #1,\\,#2 \\right]",
  "\\sqbk": "\\left[ #1 \\right]",
  "\\sqrtfrac": "\\sqrt{\\frac{#1}{#2}}",
  "\\sqrtg": "\\sqrt{g}",
  "\\sqrttwopi": "\\sqrt{\\twopi}",
  "\\srto": "\\Rightarrow",
  "\\stateA": "\\calS_{\\calA}",
  "\\stbbN": "\\st{\\bbN}",
  "\\stbbR": "\\st{\\bbR}",
  "\\stensor": "\\otimes_{\\mathrm{s}}",
  "\\stmapmu": "\\setSymbolUpLeft{\\circ}{\\mu}",
  "\\stmap": "\\setSymbolUpLeft{\\circ}{#1}",
  "\\sto": "\\xrightarrow{\\mathrm{s}}",
  "\\stsh": "\\mathcal{O}",
  "\\st": "\\setSymbolUpLeft{\\rmst}{#1}",
  "\\sumcomb": "\\sum_{\\mathrm{comb}}",
  "\\sumfour": "\\mathop{\\mathop{\\mathop{\\sum_{#1}}_{#2}}_{#3}}_{#4}",
  "\\sumiI": "\\sum_{i \\in I}",
  "\\sumjJ": "\\sum_{j \\in J}",
  "\\sumonetoinfty": "\\sum_{#1 = 1}^{\\infty}",
  "\\sumthree": "\\mathop{\\mathop{\\sum_{#1}}_{#2}}_{#3}",
  "\\sumtwo": "\\mathop{\\sum_{#1}}_{#2}",
  "\\sumzerotoinfty": "\\sum_{#1 = 0}^{\\infty}",
  "\\tHel": "\\tilde{H}_{\\mathrm{el}}",
  "\\tangentspace": "T_{#1} #2",
  "\\testfunctionOmega": "\\calD (\\Omega)",
  "\\testfunctionbbRN": "\\calD (\\bbRN)",
  "\\testfunctionbbRd": "\\calD (\\bbRd)",
  "\\tildecalUbbR": "\\tilde{\\calU}(\\bbR)",
  "\\transpose": "\\setSymbolUpLeft{t}{#1}",
  "\\transposition": "(#1 \\, #2)",
  "\\tti": "t \\to \\infty",
  "\\twonorms": "\\Vert #1 \\Vert_2",
  "\\twonorm": "\\norm{ #1 }_2",
  "\\twopii": "2 \\pi i",
  "\\twopi": "2 \\pi",
  "\\unitclosedballX": "X_1",
  "\\unitclosedballdualX": "\\dualX_1",
  "\\unitclosedball": "#1_1",
  "\\upbf": "\\textup{\\textbf{#1}}",
  "\\uto": "\\xrightarrow{\\mathrm{u}}",
  "\\uwlimntoinfty": "\\mathrm{uw} \\myhyphen \\lim_{\\nti}",
  "\\uwto": "\\xrightarrow{\\mathrm{uw}}",
  "\\vecbk": "\\rbk{#1}",
  "\\vecc": "\\begin{pmatrix}#1\\\\#2\\\\#3\\end{pmatrix}",
  "\\vecr": "\\rbk{#1,\\quad#2,\\quad#3}",
  "\\vecthreetr": "\\transpose{\\rbk{#1, #2, #3}}",
  "\\vecthree": "\\begin{pmatrix}#1\\\\#2\\\\#3\\end{pmatrix}",
  "\\vectorA": "\\boldsymbol{A}",
  "\\vectorB": "\\boldsymbol{B}",
  "\\vectorC": "\\boldsymbol{C}",
  "\\vectorD": "\\boldsymbol{D}",
  "\\vectorE": "\\boldsymbol{E}",
  "\\vectorF": "\\boldsymbol{F}",
  "\\vectorG": "\\boldsymbol{G}",
  "\\vectorH": "\\boldsymbol{H}",
  "\\vectorI": "\\boldsymbol{I}",
  "\\vectorJ": "\\boldsymbol{J}",
  "\\vectorK": "\\boldsymbol{K}",
  "\\vectorL": "\\boldsymbol{L}",
  "\\vectorM": "\\boldsymbol{M}",
  "\\vectorN": "\\boldsymbol{N}",
  "\\vectorO": "\\boldsymbol{O}",
  "\\vectorP": "\\boldsymbol{P}",
  "\\vectorQ": "\\boldsymbol{Q}",
  "\\vectorR": "\\boldsymbol{R}",
  "\\vectorS": "\\boldsymbol{S}",
  "\\vectorT": "\\boldsymbol{T}",
  "\\vectorU": "\\boldsymbol{U}",
  "\\vectorV": "\\boldsymbol{V}",
  "\\vectorW": "\\boldsymbol{W}",
  "\\vectorX": "\\boldsymbol{X}",
  "\\vectorY": "\\boldsymbol{Y}",
  "\\vectorZ": "\\boldsymbol{Z}",
  "\\vectora": "\\boldsymbol{a}",
  "\\vectorb": "\\boldsymbol{b}",
  "\\vectorc": "\\boldsymbol{c}",
  "\\vectord": "\\boldsymbol{d}",
  "\\vectore": "\\boldsymbol{e}",
  "\\vectorf": "\\boldsymbol{f}",
  "\\vectorg": "\\boldsymbol{g}",
  "\\vectorh": "\\boldsymbol{h}",
  "\\vectori": "\\boldsymbol{i}",
  "\\vectorj": "\\boldsymbol{j}",
  "\\vectork": "\\boldsymbol{k}",
  "\\vectorl": "\\boldsymbol{l}",
  "\\vectorm": "\\boldsymbol{m}",
  "\\vectorn": "\\boldsymbol{n}",
  "\\vectoromega": "\\boldsymbol{\\omega}",
  "\\vectoro": "\\boldsymbol{o}",
  "\\vectorproduct": "#1 \\times #2",
  "\\vectorp": "\\boldsymbol{p}",
  "\\vectorq": "\\boldsymbol{q}",
  "\\vectorr": "\\boldsymbol{r}",
  "\\vectors": "\\boldsymbol{s}",
  "\\vectort": "\\boldsymbol{t}",
  "\\vectoru": "\\boldsymbol{u}",
  "\\vectorv": "\\boldsymbol{v}",
  "\\vectorw": "\\boldsymbol{w}",
  "\\vectorx": "\\boldsymbol{x}",
  "\\vectory": "\\boldsymbol{y}",
  "\\vectorz": "\\boldsymbol{z}",
  "\\vectoralpha": "\\boldsymbol{\\alpha}",
  "\\vectorbeta": "\\boldsymbol{\\beta}",
  "\\vectorgamma": "\\boldsymbol{\\gamma}",
  "\\vectordelta": "\\boldsymbol{\\delta}",
  "\\vectorepsilon": "\\boldsymbol{\\epsilon}",
  "\\vectorzeta": "\\boldsymbol{\\zeta}",
  "\\vectoreta": "\\boldsymbol{\\eta}",
  "\\vectortheta": "\\boldsymbol{\\theta}",
  "\\vectoriota": "\\boldsymbol{\\iota}",
  "\\vectorkappa": "\\boldsymbol{\\kappa}",
  "\\vectorlambda": "\\boldsymbol{\\lambda}",
  "\\vectormu": "\\boldsymbol{\\mu}",
  "\\vectornu": "\\boldsymbol{\\nu}",
  "\\vectorxi": "\\boldsymbol{\\xi}",
  "\\vectorpi": "\\boldsymbol{\\pi}",
  "\\vectorrho": "\\boldsymbol{\\rho}",
  "\\vectorsigma": "\\boldsymbol{\\sigma}",
  "\\vectortau": "\\boldsymbol{\\tau}",
  "\\vectorupsilon": "\\boldsymbol{\\upsilon}",
  "\\vectorphi": "\\boldsymbol{\\phi}",
  "\\vectorchi": "\\boldsymbol{\\chi}",
  "\\vectorpsi": "\\boldsymbol{\\psi}",
  "\\vectwotr": "\\transpose{\\rbk{#1, #2}}",
  "\\vectwo": "\\begin{pmatrix}#1\\\\#2\\end{pmatrix}",
  "\\vftodfbk": "\\rbk{#1}^{\\flat}",
  "\\vftodfone": "#1^{\\flat_1}",
  "\\vftodftwo": "#1^{\\flat_2}",
  "\\vftodf": "#1^{\\flat}",
  "\\wick": ":#1:",
  "\\wlimntoinfty": "\\mathrm{w} \\myhyphen \\lim_{\\nti}",
  "\\wstar": "w^{*}",
  "\\wto": "\\xrightarrow{\\mathrm{w}}",
  "\\xix": "x \\in X",
  "\\xk": "(x_{n (k)})_{k{\\in}{\\bN}}",
  "\\xm": "(x_m)_{m{\\in}{\\bN}}",
  "\\xn": "(x_n)_{n{\\in}{\\bN}}",
  "\\xti": "x \\to \\infty",
  "\\yn": "(y_n)_{n{\\in}{\\bN}}",
};
